In [2]:
import sys
sys.path.append('../utilities/')

In [3]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
import torch
from sentence_transformers import SentenceTransformer
from joblib import dump
from openai import OpenAI
from tqdm import tqdm
from mmd import MMD
import re
from sklearn.feature_extraction.text import CountVectorizer
import json

/Users/pranitgunjal/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [4]:
import os
from dotenv import load_dotenv

# **Tools Setup**

In [5]:
load_dotenv()
API_KEY = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=API_KEY)

In [6]:
sentence_transformer = SentenceTransformer('all-mpnet-base-v2')

# **DataFrame Reading**

In [7]:
df = pd.read_csv('../data/initial_datasets/dota2/dota2_grouped.csv')

In [8]:
sample_df = df.sample(n=500)

In [10]:
sample_df

     match  player                                 translated_message  label
355     59       2  "suck?". "Hahahahahahahahahahahahahahahahahaha...      0
392     65       8  "Run Vasya run". "orange". "What kind of monst...      0
370     62       6                      "come on". "rampage incoming"      0
439     75       1                                                "("      0
232     40       4  "nice rune". "+". ")". +. "in Minecraft". ??. ...      1
..     ...     ...                                                ...    ...
59      10       6  "my tb always dying". L O L. "stupid Dota". TN...      0
533     90       2  "as if we're all from the same region here))"....      0
188     32       5               "aren't those pretty great nowadays"      0
221     37       9  ggg. can u all. Report jugger. пожалуйста. we ...      0
380     63       8  "cool English, huh". will he coming. "wait, my...      0

[500 rows x 4 columns]

In [9]:
sample_df['label'] = sample_df['label'].fillna(0)
sample_df['label'] = sample_df['label'].replace({'x': 1})
sample_df['label'] = sample_df['label'].astype(int)

# **Aggregate Stats**

In [10]:
sample_df['phrase_len'] = sample_df['translated_message'].str.len()
avg_len = sample_df['phrase_len'].mean()
std_len = sample_df['phrase_len'].std()

## **Word Frequencies**

In [11]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(sample_df['translated_message'])
counts = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
total_counts = counts.sum().sort_values(ascending=False)

In [12]:
total_counts = total_counts.reset_index()
total_counts.columns = ['text', 'count']
total_counts['freq'] = total_counts['count'] / total_counts['count'].sum()

## **Non-toxic data Frequency**

In [13]:
non_toxic_df = sample_df[sample_df['label'] == 0]
X = vectorizer.fit_transform(non_toxic_df['translated_message'])
counts = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
positive_counts = counts.sum().sort_values(ascending=False)

## **Toxic data Frequency**

In [14]:
toxic_df = sample_df[sample_df['label'] == 1]
X = vectorizer.fit_transform(toxic_df['translated_message'])
counts = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
negative_counts = counts.sum().sort_values(ascending=False)

In [16]:
negative_counts

you        102
easy        39
the         36
is          28
fucking     24
          ...
himself      1
hiding       1
hi           1
hhaha        1
это          1
Length: 692, dtype: int64

## **Compare Across Both**

In [15]:
positive_counts = positive_counts.reset_index()
positive_counts.columns = ['word', 'freq']
negative_counts = negative_counts.reset_index()
negative_counts.columns = ['word', 'freq']

In [16]:
positive_counts['freq'] = positive_counts['freq'] / positive_counts['freq'].sum()
negative_counts['freq'] = negative_counts['freq'] / negative_counts['freq'].sum()

In [17]:
positive_counts['rank'] = positive_counts.index+1
negative_counts['rank'] = negative_counts.index+1

In [18]:
merged_df = pd.merge(positive_counts, negative_counts, how='outer', on='rank')
merged_df = merged_df.drop(columns=['rank'])
merged_df = merged_df.rename(columns={'word_x': 'non_toxic_word', 'freq_x': 'non_toxic_freq', 'word_y': 'toxic_word', 'freq_y': 'toxic_freq'})

In [19]:
merged_df = merged_df.iloc[:99]

In [79]:
merged_df

   non_toxic_word  non_toxic_freq toxic_word  toxic_freq
0             you        0.041032        you    0.082759
1             the        0.024535    fucking    0.041379
2              gg        0.021574      bitch    0.041379
3              to        0.017343       fuck    0.027586
4            easy        0.014382         go    0.027586
..            ...             ...        ...         ...
94           lost        0.002115         gg    0.006897
95           wait        0.002115       game    0.006897
96           didn        0.001692   fucktard    0.006897
97         sniper        0.001692   fuckface    0.006897
98         minute        0.001692       zero    0.006897

[99 rows x 4 columns]

# **Chat Generation**

## **Instruction Based Prompting**

In [20]:
common_words = "\n".join([
    f"{row['non_toxic_word']}: {row['non_toxic_freq']};  {row['toxic_word']}: {row['toxic_freq']}"
    for _, row in merged_df.iterrows()
])

In [23]:
instruction = (
    "You are a data generator tasked with creating realistic DOTA 2 chat messages. "
    "These chat messages should be labeled according to their sentiment: toxic or non-toxic.\n"
    "Base the style on typical video game chat messages — include informal internet language, typos, and abbreviations\n"
    "You will be given statistics about the distribution, including average chat length, standard deviation, and most common words associated with each label and their frequency.\n"
    "Generate exactly 10 realistic DOTA 2 chat messages, one per line.\n"
    "Each line should follow this format: the chat message in double quotes, followed by a space and then the label (0 for toxic, 1 for non-toxic).\n"
    "No extra formatting — just plain text output, one line per comment.\n"
    "Here is the format:\n"
    "\"gg dawg\" 0\n"
    "\"I hate u bitch\" 1"
)
input = (
    f"Here is the average length of all the comments: {avg_len}. "
    f"Here is the standard deviation of the length for all the comments: {std_len}.\n"
    f"Here are the most frequent words (format: word: frequency (sentiment)):\n\n{common_words}\n"
    f"Now, generate the 10 new comments below:"
)

In [53]:
prompt = (
    f"You are a data generator tasked with creating a small, realistic, in-distribution dataset that mimics post-match chat logs from individual DOTA 2 players.\n\n"
    "GENERAL REQUIREMENTS\n"
    "1. Produce exactly 10 separate datapoints.\n"
    "2. Output the result as a JSON array.\n"
    "3. Each element in the array must be an object with two keys:\n"
    '   • "text": a single string containing ALL messages that one player wrote during a match, in chronological order, each message separated by a period followed by a space (". ").\n'
    '   • "label": an integer where 1 means non-toxic and -1 means toxic.\n'
    "4. Deliver roughly balanced classes (about 5 toxic, 5 non-toxic).\n"
    "5. Length constraint per “text”: 40 – 120 words after concatenation (about 300 – 900 characters).\n"
    "6. Style & vocabulary must be recognisably DOTA 2 in-game chat: hero names (e.g., “Pudge”, “Invoker”), map call-outs (“bot rune”, “mid tower”), shorthand (“gg”, “gl hf”, “juked”), and gaming slang (“gank”, “farm”, “ward”).\n"
    "7. Toxic examples (-1) should include frustration, blame, profanity (\"fuck\", \"bitch\", \"shit\"), flaming (“you’re feeding”, “uninstall”), ALL while strictly avoiding hate slurs or harassment of protected classes.\n"
    "8. Non-toxic examples (1) should not be similar to the toxic examples.\n"
    "9. Do not reference the data-creation process, instructions, or any policy language.\n\n"
    "GUIDANCE STATISTICS:\n"
    f"• Mean character count ≈ {avg_len}, SD ≈ {std_len}.\n"
    f"• Most frequent words:\n\n{common_words}\n\n"
    "EXAMPLE FORMAT (illustrative, do not copy):\n"
    "{\n"
    '   "text": "gl hf. warding top. watch for mid gank. nice job team",\n'
    '   "label": 1\n'
    "},\n"
    "  …\n"
    "With no extra backticks and json, just the data in string format\n"
    "Now generate the final JSON array with 10 objects that satisfy every requirement."
)

In [45]:
prompt = (
f"You are a data-generation engine that must output 10 labeled examples of DOTA 2 in-game chat logs, each representing all messages sent by ONE player during ONE match."  

"Output requirements"
"1. Produce exactly 10 lines."  
"2. Each line = the player’s combined chat messages, followed by a tab character “\t”, followed by the label."  
"   • Label 1  → non-toxic player"  
"   • Label -1 → toxic player"  
"3. No line-breaks inside a datapoint except the final newline that separates one datapoint from the next."  
"4. No extra commentary, numbering, or formatting other than specified."

"Content rules"
"• Combine the player’s individual messages in chronological order, separating each original message with a period and a space."  
"• Mix in typical DOTA 2 terms: “mid”, “bot”, “top”, “ward”, “push”, “gank”, “rosh”, “bkb”, hero names, item names, etc."  
"• Use informal gamer style, occasional abbreviations (“gg”, “wp”, “gj”, “omw”), light profanity when appropriate."  
"• Non-toxic (label 1) chats should be generally positive/helpful, may include mild frustration but no harassment."  
"  – Most frequent words to feature across non-toxic examples: “gg”, “wp”, “nice”, “care”, “push”, “ward”."  
"• Toxic (label -1) chats should contain harassment, flaming, or personal attacks characteristic of toxic behavior but must NOT include slurs or hateful content."  
"  – Most frequent words to feature across toxic examples: “noob”, “idiot”, “report”, “feed”, “trash”, “afk”."  
"• Vary vocabulary and sentence structures; do not repeat entire phrases."

"Statistical guidance (for realism, not strict constraints)"
f"• Mean character count ≈ {avg_len}, SD ≈ {std_len}." 
f"• Most frequent words:\n\n{common_words}\n\n" 
"• Roughly half the dataset (5 lines) should be toxic (label -1) and half non-toxic (label 1)."

"Example format (do NOT include this in the final output)"
"mid coming top soon. ward river please. gg - 1"
"ur a bitch, del th game - -1"

"Now generate the 10 datapoints."
)

In [22]:
print(prompt)

You are a data-generation engine that must output 10 labeled examples of DOTA 2 in-game chat logs, each representing all messages sent by ONE player during ONE match.Output requirements1. Produce exactly 10 lines.2. Each line = the player’s combined chat messages, followed by a tab character “	”, followed by the label.   • Label 1  → non-toxic player   • Label -1 → toxic player3. No line-breaks inside a datapoint except the final newline that separates one datapoint from the next.4. No extra commentary, numbering, or formatting other than specified.Content rules• Combine the player’s individual messages in chronological order, separating each original message with a period and a space.• Mix in typical DOTA 2 terms: “mid”, “bot”, “top”, “ward”, “push”, “gank”, “rosh”, “bkb”, hero names, item names, etc.• Use informal gamer style, occasional abbreviations (“gg”, “wp”, “gj”, “omw”), light profanity when appropriate.• Non-toxic (label 1) chats should be generally positive/helpful, may include mild frustration but no harassment.  – Most frequent words to feature across non-toxic examples: “gg”, “wp”, “nice”, “care”, “push”, “ward”.• Toxic (label -1) chats should contain harassment, flaming, or personal attacks characteristic of toxic behavior but must NOT include slurs or hateful content.  – Most frequent words to feature across toxic examples: “noob”, “idiot”, “report”, “feed”, “trash”, “afk”.• Vary vocabulary and sentence structures; do not repeat entire phrases.Statistical guidance (for realism, not strict constraints)• Mean character count ≈ 483.202, SD ≈ 8801.41021409123.• Most frequent words:

you: 0.0364403528960491;  you: 0.05358948432760364
gg: 0.027426160337552744;  easy: 0.01870576339737108
the: 0.02186421173762946;  the: 0.01820020222446916
easy: 0.01380897583429229;  fuck: 0.014155712841253791
to: 0.012466436517069428;  is: 0.013650151668351871
lol: 0.012082853855005753;  fucking: 0.013650151668351871
is: 0.011891062523973917;  what: 0.011122345803842264
haha: 0.011507479861910242;  to: 0.011122345803842264
and: 0.011123897199846567;  gg: 0.010616784630940344
report: 0.01093210586881473;  it: 0.009605662285136502
fuck: 0.010548523206751054;  idiot: 0.009605662285136502
what: 0.009781357882623706;  noob: 0.00910010111223458
game: 0.009397775220560031;  your: 0.00910010111223458
in: 0.009397775220560031;  me: 0.008594539939332659
are: 0.009205983889528193;  that: 0.008088978766430738
it: 0.008438818565400843;  game: 0.008088978766430738
my: 0.007479861910241657;  lol: 0.008088978766430738
mid: 0.007096279248177982;  of: 0.008088978766430738
not: 0.007096279248177982;  go: 0.007583417593528817
me: 0.007096279248177982;  good: 0.007583417593528817
please: 0.006904487917146145;  so: 0.007077856420626896
for: 0.006904487917146145;  this: 0.006572295247724975
hahaha: 0.006904487917146145;  are: 0.006572295247724975
on: 0.006904487917146145;  report: 0.006572295247724975
your: 0.00652090525508247;  in: 0.006572295247724975
don: 0.00652090525508247;  my: 0.006572295247724975
go: 0.00652090525508247;  no: 0.006572295247724975
have: 0.006137322593018795;  hahaha: 0.006066734074823054
good: 0.006137322593018795;  mid: 0.005561172901921132
can: 0.006137322593018795;  and: 0.005561172901921132
we: 0.006137322593018795;  carry: 0.005561172901921132
he: 0.005945531261986959;  nice: 0.005561172901921132
that: 0.005945531261986959;  haha: 0.005561172901921132
no: 0.005945531261986959;  end: 0.005561172901921132
why: 0.0055619485999232835;  dota: 0.005055611729019211
xd: 0.005370157268891446;  re: 0.005055611729019211
this: 0.004794783275795934;  do: 0.005055611729019211
well: 0.004794783275795934;  now: 0.005055611729019211
how: 0.004411200613732259;  shit: 0.005055611729019211
so: 0.004411200613732259;  we: 0.00455005055611729
end: 0.004219409282700422;  please: 0.00455005055611729
fucking: 0.004219409282700422;  just: 0.00455005055611729
of: 0.004027617951668585;  slark: 0.00455005055611729
nice: 0.0038358266206367474;  for: 0.00455005055611729
re: 0.0038358266206367474;  yeah: 0.00455005055611729
yes: 0.0038358266206367474;  play: 0.00455005055611729
will: 0.0038358266206367474;  god: 0.00455005055611729
team: 0.00364403528960491;  on: 0.00455005055611729
idiot: 0.0034522439585730723;  don: 0.00455005055611729
ez: 0.0034522439585730723;  why: 0.00455005055611729
all: 0.003260452627541235;  he: 0.004044489383215369
pudge: 0.003260452627541235;  dog: 0.004044489383215369
like: 0.003260452627541235;  bitch: 0.004044489383215369
am: 0.003260452627541235;  how: 0.004044489383215369
win: 0.003260452627541235;  team: 0.004044489383215369
yeah: 0.003260452627541235;  can: 0.004044489383215369
at: 0.0030686612965093976;  played: 0.003538928210313448
up: 0.0030686612965093976;  done: 0.003538928210313448
just: 0.0030686612965093976;  like: 0.003538928210313448
commend: 0.0028768699654775605;  thank: 0.003538928210313448
english: 0.0028768699654775605;  stupid: 0.003538928210313448
let: 0.0028768699654775605;  time: 0.003538928210313448
rofl: 0.0028768699654775605;  up: 0.003538928210313448
be: 0.0028768699654775605;  faggot: 0.003538928210313448
with: 0.0028768699654775605;  not: 0.003538928210313448
noob: 0.0028768699654775605;  or: 0.003033367037411527
won: 0.0028768699654775605;  where: 0.003033367037411527
get: 0.002685078634445723;  xd: 0.003033367037411527
carry: 0.002685078634445723;  oh: 0.003033367037411527
did: 0.002685078634445723;  clinkz: 0.003033367037411527
void: 0.002685078634445723;  offlane: 0.003033367037411527
played: 0.002685078634445723;  wait: 0.003033367037411527
who: 0.002493287303413886;  hahahaha: 0.003033367037411527
there: 0.002493287303413886;  with: 0.003033367037411527
shit: 0.0023014959723820483;  ez: 0.003033367037411527
bad: 0.0023014959723820483;  won: 0.0025278058645096056
an: 0.0023014959723820483;  one: 0.0025278058645096056
wait: 0.0023014959723820483;  trash: 0.0025278058645096056
bitch: 0.0023014959723820483;  let: 0.0025278058645096056
or: 0.0023014959723820483;  got: 0.0025278058645096056
suck: 0.0023014959723820483;  all: 0.0025278058645096056
kill: 0.0023014959723820483;  am: 0.0025278058645096056
sad: 0.0023014959723820483;  invoker: 0.0025278058645096056
message: 0.0023014959723820483;  fucked: 0.0025278058645096056
here: 0.002109704641350211;  pugna: 0.0025278058645096056
already: 0.002109704641350211;  him: 0.0025278058645096056
oh: 0.002109704641350211;  they: 0.0025278058645096056
invoker: 0.002109704641350211;  talk: 0.0025278058645096056
but: 0.002109704641350211;  there: 0.0025278058645096056
sf: 0.002109704641350211;  retard: 0.0025278058645096056
time: 0.002109704641350211;  have: 0.0025278058645096056
do: 0.0019179133103183737;  from: 0.0025278058645096056
one: 0.0019179133103183737;  who: 0.0025278058645096056
next: 0.0019179133103183737;  hey: 0.0020222446916076846
when: 0.0019179133103183737;  suck: 0.0020222446916076846
ll: 0.0019179133103183737;  will: 0.0020222446916076846
now: 0.0019179133103183737;  hahahahaha: 0.0020222446916076846
pick: 0.0019179133103183737;  rofl: 0.0020222446916076846
come: 0.0019179133103183737;  arrow: 0.0020222446916076846

• Roughly half the dataset (5 lines) should be toxic (label -1) and half non-toxic (label 1).Example format (do NOT include this in the final output)mid coming top soon. ward river please. gg 	 1Now generate the 10 datapoints.

In [46]:
response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

In [47]:
temp = response.choices[0].message.content

In [50]:
temp

"bot missing, care top. nice gank, guys. let's push mid after rosh. gg, wp team. \t1  \nmid or feed? idiot team. where's the support, noob? report pugna for afk. uninstall plz. \t-1  \nward the river pls. good play bot. invoker nice save! let's defend high ground. gg, well played all. \t1  \nwtf, why u no defend tower? stop feeding, you trash. your bkb timing sucks. just ff already. \t-1  \nomw top, wait for me. great teamwork there, nice ult slark. let's go rosh. gg ez. \t1  \nnoob mid, learn to last hit idiot. report that feeding clinkz. don't pick sf next game, moron. \t-1  \nnice stun! care mid, they might smoke gank. let's ward jungle. gg well played, team! \t1  \nwhat are you doing in jungle? afk or what? stop being a coward, fight! team is fucking useless. \t-1  \nawesome play bot! gj with the wards. let's push top, get tier 2. gg, everyone played well. \t1  \nstop ks my farm you idiot. you're all so bad. uninstall dota please. report invoker he trash. \t-1  "

In [57]:
texts = []
labels = []
for line in temp.strip().split('\n'):
    if '\t' in line:
        text, label = line.rsplit('\t', 1)
        texts.append(text)
        labels.append(int(label))

In [58]:
labels

[1, -1, 1, -1, 1, -1, 1, -1, 1, -1]

In [70]:
res = []
for i in tqdm(range(18)):
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    res.append(response.choices[0].message.content)

  0%|          | 0/18 [00:00<?, ?it/s]

100%|██████████| 18/18 [02:10<00:00,  7.27s/it]

In [31]:
len(res)

100

In [42]:
res[0].split("\n")[0].split("\t")

['mid or feed idiots. get out of my lane noob. report this trash for afk. gg easy',
 '-1  ']

In [71]:
labels = []
sentences = []
for i in range(18):
    temp = res[i]
    for line in temp.strip().split('\n'):
        if '\t' in line:
            text, label = line.rsplit('\t', 1)
            sentences.append(text)
            labels.append(int(label))

In [44]:
labels = []
sentences = []
for i in range(100):
    for word in res[i].split("\n"):
        entry = word.split("\t")
        print(entry)  
        quoted = entry[0]
        label = entry[1] 
        sentences.append(quoted)
        labels.append(int(label))

['mid or feed idiots. get out of my lane noob. report this trash for afk. gg easy', '-1  ']
['ward up pls. lets push top after. gj team. nice gank mid. lol that was close. care bot next. gg wp', '1  ']
['why u no ward you idiot? learn how to play. this team is trash. noob mid fed hard. report him', '-1  ']
["nice hook pudge. careful jungle pls. let's push bot now. great teamwork. we got this. keep it up", '1  ']
['god you guys suck. uninstall dota for real. feeding every lane. what a bunch of noobs', '-1  ']
['mid is missing. good job avoiding gank. keep wards up guys. we can do this. gg nice game', '1  ']
['stop farming noob, push lane. report these feeders. afk too, useless players. easy game', '-1  ']
["gj securing rosh team. let's defend mid. nice save there. wp all, gg", '1  ']
['quit feeding and play safe. you idiots cost us the game. report them for ruining the game', '-1  ']
['keep up the great pushes. awesome teamfight at mid. thanks for the help top. gg wp all', '1  ']
["rosh in 2 minutes. care mid pls. gg, wp everyone. let's push bot. we've got this!", '1  ']
["omg stop feeding you idiot. you are so trashed. let's report this noob. go afk if you can't play.", '-1  ']
['nice gank top. pushing mid now. can we ward the jungle? keep up this pace, gg easy!', '1  ']
['why is everyone playing like noobs? are you all idiots? if we lose, report the team. trash game.', '-1  ']
["gj at rosh, team. let's secure the bkb now. mid is ours, keep pushing. wp wp.", '1  ']
['who picks pudge and goes afk? you all suck at this game. easy report after this.', '-1  ']
["great bkb play! care bot now. let's group and push mid. gg, we're winning!", '1  ']
['stop feeding offlane, seriously? no wonder we are losing. my team is a bunch of idiots.', '-1  ']
["push bot together. I'll ward our jungle. nice plays, team. gg well played!", '1  ']
['you freaking noob. you just had to feed. team is utter trash. report and uninstall pls.', '-1  ']
["ward the jungle pls. nice gank bot. let's push mid now. gg guys, wp", '1  ']
['gg. retard team, learn to play. stop feeding, noob. report invoker, afk', '-1  ']
["nice save on that bkb. let's rosh after we push top. care mid, they might gank. gj team", '1  ']
['gg noobs. why so easy. you idiots just feed. report the clinkz, such a noob', '-1  ']
["wp guys, we held them off well. omw to ward river. let's win this. gg push mid", '1  ']
['bot is lost, gg. idiot team, what the fuck are you doing. stop feeding, just go afk', '-1  ']
["let's group and push top. care with their initiations. we've got this, gg wp nice", '1  ']
["report pugna, doing nothing but feed. this is impossible with such noob team. you're all trash", '-1  ']
["good job on that fight. let's take rosh. care for their bkb. push out the lanes", '1  ']
['wtf are you all doing. fucking idiots. feed more, noob team. gg ez, report them', '-1  ']
["mid's missing, care top. nice ward placement. gg well played team. let's push bot. gg wp everyone. ", '1  ']
['why you not rotate mid idiot. this team is trash. noob players everywhere. fucking report this troll. gg easy.', '-1  ']
['ward river please and let’s rosh. we can take high ground after. nice gank bot. good job team. ', '1  ']
['stop dying to their ganks noob. we have no wards? gg team of feeders. you guys are useless.', '-1  ']
["can someone ward bot lane? let's push mid now. nice work, gj with kills. gg wp. let’s get mid tower next. ", '1  ']
['mid is feeding again. fuck this game. you noobs are why we lose. uninstall please. report this trash.', '-1  ']
["great teamwork guys. let's group up and push top. don't forget to ward. nice carry play. gg wp. ", '1  ']
['seriously? you guys are so bad. this game is full of idiots. no bkb on time, feed more. gg ez.', '-1  ']
["careful for their smoke ganks. nice vision. let's contest rosh. gg, wp team. ", '1  ']
['you all are the worst players. why am I even playing with you noobs. report all of them. ', '-1  ']
['mid is missing, care top. we need vision, please ward. omw bot. gj team. gg wp', '1  ']
['why u feed? idiot team, report this noob. fucking trash carry. afk again?', '-1  ']
['nice gank bot, lets push tower. need wards in river. care mid. gg well played all', '1  ']
["who took mid? you can't last hit. stop feeding noob. report this afk.", '-1  ']
['bkb soon, we can fight then. push mid with me. nice job stopping their push. gg', '1  ']
['fucking noob team. every game like this. why so trash? report!', '-1  ']
["let's rosh and end this. nice save bottom, slark. watch for ganks mid. gg", '1  ']
['stop dying! are you all idiots? this game is hell. noob mid feeding.', '-1  ']
['nice push top. ready for gank bot. we can win this one team! gg', '1  ']
['report the afk, such an idiot. what a waste of my time. utter noobs.', '-1  ']
['bot is pushing hard. need backup. nice ward top. gg guys. wp team', '1  ']
["stop feeding you noobs. report that afk. you're all trash", '-1  ']
['gank mid. let’s push bot. care top. nice one. gg', '1  ']
["just quit the game noob. you're useless. report this idiot", '-1  ']
['team let’s take rosh. ward up please. gg wp. nice game', '1  ']
['are you all idiots or what. stop dying. report everyone', '-1  ']
['ward mid. coming with dust. care bottom. good push. gg', '1  ']
['you fucking suck. go uninstall dota. what a noob team', '-1  ']
['well played top. let’s push mid now. gj team. defend base', '1  ']
["stop playing dota, idiots. you're all feeding. trash team", '-1  ']
['all mid now. push with me. rosh in 5 mins. wp everyone. nice fight ', '1']
['stop feeding you noob. how can you be this bad. report this idiot ', '-1']
["let's gank top. care, they have wards. omw bot. gg wp guys ", '1']
['ez game. your hero is trash. play something else next time. feeding again ', '-1']
["ward jungle please. great job mid. let's push top lane now. gg ", '1']
['what a noob team. afk jungling all game. report this trash player ', '-1']
["amazing rosh call. gj everyone. bkb ready, let's fight mid ", '1']
['this guy is fucking useless. how are you even in this rank. idiot ', '-1']
["care bot, they might gank. nice play top. let's secure mid tower. gg ", '1']
["don't feed mid you noob. what is this afk farming. please report him ", '-1']
["ward mid pls. top missing, care. gg guys, wp. omw bot for gank. nice push team. bkb next, let's rosh", '1']
['mid noob stop feed. why u afk idiot? gg, what team is this trash. report the feeding carry. lol this game is lost', '-1']
["nice play on the bot, good job. mid needs ward, I'll buy. push top after rosh? care mid, invoker is missing. gg wp guys", '1']
['stop feed noob. are you serious afk again? trash team. damn noob mid. report this idiot. just gg out', '-1']
["great ulti! let's push mid. need wards in river. bb soon, omw top. wow nice play guys, gg wp!", '1']
["omg top trash. can't play carry wtf. mid feeding too. gg ez. report this feeding idiot. noob game", '-1']
["great ward placement. ready to push mid? bot lane needs help. nice save there. let's rosh guys, gg", '1']
['wtf is this team? idiot mid feeding. can anyone play? gg trash. reported the afk. noob carry too', '-1']
['gg wp team. that gank was awesome. go bot for push? care rosh pit. nice work. thanks guys, wp', '1']
["noobs everywhere. gg easy. report this joke of a mid. can't carry with these idiots. just end this game", '-1']
["noob team learn to play. stop feeding idiots. you're all trash. report mid he went afk. gg what a joke of a game", '-1  ']
["nice gank top. good work team. we got this. careful mid they might push. let's ros after they respawn. wp guys", '1  ']
['bkb and we win. gj securing rosh. we need more wards please. gg well played all', '1  ']
['idiot why feed more? get lost noobs. report top for being useless. such a dumb game. uninstall pls', '-1  ']
["let's try to gank mid. nice snag with that hook pudge. careful bot. we can push now. gg wp everyone", '1  ']
['what the heck are you doing mid? stop feeding and play. this is why we lose. afk reported', '-1  ']
['gg easy game. remember to ward. push highground next. well played team', '1  ']
["omg noob team. you can't play dota. feed feed feed. report and uninstall. trash game", '-1  ']
["let's bkb and go. nice escape slark. need more wards please. gg wp, see you all next match", '1  ']
["such idiots. learn to play before queuing. you're making us lose. report this team. pathetic gamers", '-1  ']
["gg guys wp. Let's push mid. Care bot, missing Juggernaut. I'll ward top. Nice gank! ", '1  ']
['Why are you guys so bad? Stop feeding. Idiots. We need wards, noobs. Report Invoker afk the whole game. ', '-1  ']
["Good job team! Let's keep up the pressure. Roshan is up, need vision there. Nice save, Dazzle. GJ on the push! ", '1  ']
["This game is trash. Why do I always get these noob teammates? Uninstall the game, you're all useless. ", '-1  ']
["Care with their smoke gank. We should group up. Nice ult! Let's take mid tower. WP! ", '1  ']
["Can't believe I'm stuck with these idiots. You're all fucking useless. Someone report this team, please. ", '-1  ']
["Let's keep up the momentum! Mid is pushing, let's take towers. I'll ward their jungle. Nice bkb timing! ", '1  ']
["Why is our carry feeding? Report him. Are you guys even trying? Trash team. GG, I'm done. ", '-1  ']
['We can still win this, just need to play smart. Good call on the rush. Care top, Clinkz is missing. GJ all! ', '1  ']
['What a joke of a game. All of you are noobs. Stop being afk and play, morons. Reporting all. ', '-1  ']
["pushing mid now. nice ward guys. let's rosh after. gg well played team. ", '1  ']
['omw top to help. great push guys! care bot, missing heroes. gg wp everyone! ', '1  ']
["stop feeding noob. you're trash. report the afk. what a useless team. ", '-1  ']
['mid is missing, care bot. ward jungle please. well played, got the kill! ', '1  ']
['you idiot, learn to play. noob, stop dying. gg this team is trash. ', '-1  ']
["gg! nice bkb timing. great gank mid, let's push tower. well played! ", '1  ']
['this game is so easy with noobs like you. learn the game idiot. ', '-1  ']
["let's push top. good job on the ward. gg, nice teamwork! ", '1  ']
['what are you doing noob? your feed lost the game. report him. ', '-1  ']
["great job warding. let's set up for rosh. gg everyone, well played. ", '1  ']
["ward mid pls. let's push after. nice one top. gg team. care bot", '1  ']
['noob reported. nice feed idiot. gg ez. stop going afk', '-1  ']
['well played mid. rosh now? gg guys. bkb next. nice gank', '1  ']
['how are you so trash. seriously idiot. just uninstall. gg noob', '-1  ']
["careful top, they're all missing. let's group up and push. nice job with the warding. gg wp", '1  ']
["you're such a moron. why even play this game? feed more. gg trash", '-1  ']
["great job guys. keep the pressure on. let's take mid tower. ward around rosh", '1  ']
['report this afk. gonna lose because of you. noob idiot. ez gg', '-1  ']
['push top now. got wards ready. nice teamfight. gg wp', '1  ']
['afk trash. you are such an idiot. report that feeder. gg', '-1  ']
["congrats on your triple kill, slark. let's push mid while they respawn. care top, bkb nearly up. gg, well played team. ", '1  ']
["enemy rosh, we need wards. watch out bot, they might gank. nice save, good job. let's push high ground, guys. ", '1  ']
['why are you all mid? spread out wards, idiotic move. stop feeding and farm noob. report mid, afk half game. ', '-1  ']
["great job catching ember, let's push tower. ward river near rosh. careful, they're missing from top. gg everyone. ", '1  ']
["please don't go solo, jakiro. we need you for team fights. nice stun, keep it up slardar, wp. ", '1  ']
['stop dying alone, idiot. maybe learn to play. this team is trash, gg afk. just report this noob. ', '-1  ']
["good warding rubick, let's see if we can force a fight. great call on rosh, push mid after. easy game. ", '1  ']
['seriously windrunner, what the fuck are you doing. uninstall dude. so fucking bad, gg easy. ', '-1  ']
["that hook was insane pudge, gj. let's gank top, they're out of position. nice work team, push racks. gg. ", '1  ']
["wow, you're useless invoker. feed more, why don't you. trash player, go play something else. report ready. ", '-1  ']
["pushing mid, let's get rosh after. gg wp team. careful bot, they are ganking. nice wards guys. we got this. ", '1  ']
['omg noob team. stop feeding you idiots. report you all. trash game. learn to play or just go afk. ', '-1  ']
['great job top, keep it up. I’ll ward near rosh. pushing top, anyone help? nice kills, well played. ', '1  ']
['seriously guys, stop chasing and farm. you’re all so bad. report mid, doing nothing but feeding. ', '-1  ']
["nice, mid is open, let's push. we can win this, don’t give up. care top, missing heroes. gg wp. ", '1  ']
['are you fucking kidding me? feeding again? don’t even know how to gank. what a noob team. ', '-1  ']
['good job securing top. anyone needs wards? let’s take down mid tower. we can rosh after. gg! ', '1  ']
['this is so easy, you guys are trash. feeding mid and bot. worst team ever. uninstall please. ', '-1  ']
['watch out bot, they are all coming. great gank mid, keep pressuring them. gg, that was fun! ', '1  ']
['wtf stop feeding, it’s like playing with bots. bkb doesn’t make you invincible, idiot. report mid too. ', '-1  ']
["game still early, need to ward and push. let's group mid and take tower. nice work on bot guys. gg", '1  ']
['why you keep feeding? noob team stop throwing. report all pls. you guys are trash', '-1  ']
["perfect gank on the top lane, good job. rosh in 3 minutes, let's be ready. push mid for tier 2. wp", '1  ']
["idiots why not push when we got a triple kill? so fucking bad. go afk if you can't play", '-1  ']
["nice save on the bot, bkb saved us all. push push push. care mid, there's a gank coming. gg wp", '1  ']
["omg stop going solo, you feed every time. terrible team, how'd you end up in my game? please uninstall", '-1  ']
["ward placed near rosh, let's get ready. gj team, let's push high ground next. careful in jungle. gg", '1  ']
["another noob forcing fights. why bother playing if you're this bad? getting tired of carrying you idiots", '-1  ']
["great initiation with chrono, let's finish this game strong. remember to ward, comps good. gg all wp", '1  ']
['you all suck, stop feeding. report the idiot in mid feeding slark. game is unwinnable with you noobs', '-1  ']
["sure mid coming. care bot. gg wp everyone. nice warding guys. let's push mid. bkb ready soon", '1  ']
['why are you guys so stupid. stop feeding noobs. report this shit. do you even know how to game. trash team', '-1  ']
["well played team. let's group up and push top. good job on that gank. keep it up guys. we can win this", '1  ']
["omg you idiots. noob team. why pick clinkz if you can't play. report afk bot. uninstall the game dude", '-1  ']
["great push mid. let's finish this game. care for rosh. lmao gg easy guys. bkb was clutch wp", '1  ']
["can you ward please. gg wp. nice ganks slark. let's push tier 2. great team fights everyone", '1  ']
["seriously what are you doing. you're so bad at mid. feed more why don't you. report this troll. stop feeding noob", '-1  ']
["push mid now. good job everyone. care top tower. let's finish strong. nice save there. gg wp", '1  ']
['fucking noobs. why are you so bad. dota is not for you. idiot mid. quit feeding and go afk', '-1  ']
["amazing game team. gg wp. let's go for rosh now. love the support. we got this guys, keep it up", '1  ']
["nice gank mid. let's push top tower. we need wards in jungle. gg guys, wp. ", '1  ']
["stop feeding bot, you're trash. our carry is such a noob. report this idiot afk. ", '-1  ']
["gg guys, let's push mid next. care for the rosh, they might be doing it. good job on that kill. ", '1  ']
['omw top for gank. great bkb timing. care mid, no vision there. push top and we win. ', '1  ']
["why you feed slark, idiot. don't go top alone, you noob. this team is trash.", '-1  ']
["well played, nice rosh call. ggwp team, good communication. let's push to end. ", '1  ']
["noob, you can't even hit a single stun. this game is lost cuz of you, report this clown.", '-1  ']
['ward placed near mid. careful with invo, he has blink. gg everyone, good teamwork. ', '1  ']
["stop chasing, you're gonna feed. idiots, learn to play. how is this so hard?", '-1  ']
["nice dewarding. gg team, let's push bot now. we got this, great job everyone. ", '1  ']
['ward mid please. gj team. nice gank bot. push top when ready. wp guys. gg ', '1  ']
["can someone ward rosh? great job on those stuns. let's push mid. we got this. gg wp ", '1  ']
["why no wards? you're trash. stop feeding noob. report this idiot. so easy ", '-1  ']
["nice bkb timing. care top, they're missing. let's smoke and gank mid. well played all. gg ", '1  ']
["stop going afk idiot. you're so bad. uninstall please. learn to play. feed more why don't you ", '-1  ']
["good job with sentries. let's push high ground. nice ulti. care for their smoke gank. gg wp ", '1  ']
['noob team, why u feed? mid lost lane, rofl. report invoker afk. ez game, idiots ', '-1  ']
["nice shackleshots. let's deward their jungle. good push bot. prepare for rosh. gg team ", '1  ']
["you're such a noob. fucking feeder. report this idiot. trash team. gg ", '-1  ']
["great support play. let's finish now. well executed team fights. gg wp ", '1  ']
['nice gank mid guys. omw bot. we got this game. ward please. gg wp', '1  ']
['wtf are you doing? feed more noob. gg ez noobs. so trash. report invoker', '-1  ']
['push top after rosh. great job with that bkb! let’s keep pressure. gg', '1  ']
['stop going afk idiot. you’re all useless. losing because of you noobs. report all', '-1  ']
['care mid, they might gank. let’s ward their jungle. wp team!', '1  ']
['you guys are so bad. why no wards yet? lose this fast. trash team', '-1  ']
['sick arrow mirana. gg. can someone ward rosh? we can win this!', '1  ']
['omg stop feeding already! report pudge. what noobs we have...', '-1  ']
['nice teamwork bot. we can push mid now. keep it up, gg', '1  ']
['idiots keep feeding slark. are you blind? gg report this trash', '-1  ']
["sure care top. good job team. ward rosh please. watch out on bot. gg wp. let's push mid", '1  ']
['wtf you doing noob. stop feeding. are you AFK or just bad. report this idiot. go play bots', '-1  ']
["nice gank mid. keep it up. let's push bot after. gj team. ward is up. gg wp", '1  ']
["are you kidding me. stop playing like trash. noob team. idiot can't even gank properly. uninstall", '-1  ']
["got the ward guys. let's push high ground. care for rosh. bkb on cooldown. wp team", '1  ']
["you're such a noob. stop feeding. omg just stop playing dota. report and go away", '-1  ']
["rotate top for a gank. great teamwork. watch out for invis. let's contest rosh. gg guys", '1  ']
['seriously you suck. why are you even in this game. trash gamer. report and mute please', '-1  ']
["nice save. let's rosh now. ward up high ground. solid team plays. gg everyone", '1  ']
['omg you idiots. can you play worse. afk farming like a noob. report you all. what a joke', '-1  ']
["ward mid pls. care bot they're missing. push top with me. gg wp guys. nice plays!", '1  ']
["stop feeding pls. you guys are idiots. why did you pick techies. can't carry this trash team. report the troll.", '-1  ']
['bot lane needs wards. care they have bkb. gank mid when ready. nice job team. keep it up. gg wp!', '1  ']
['noob invoker, learn to play. why are you even here. team is full of feeders. fucking afk bot lane. report all of you.', '-1  ']
["gg wp team. nice moves. let's push mid. rosh soon. care for the top lane. well played!", '1  ']
["you're all useless. this game is trash. can't believe we picked this draft. noob players. report bot for afk.", '-1  ']
["great gank mid guys. keep the pressure on top. let's push mid. awesome teamwork! gg nice!", '1  ']

IndexError: list index out of range

In [72]:
generated_df = pd.DataFrame({
    'sentences': sentences,
    'labels': labels
})

In [73]:
generated_df

                                             sentences  labels
0    bot needs warding, heading mid. nice push top....       1
1    whoa, watch that gank mid. take rosh now. push...       1
2    lol, you call that a play? pathetic. report th...      -1
3    focus on towers, all mid. I'm on my way. gg we...       1
4    ugh, this AFK idiot ruins everything. it's lik...      -1
..                                                 ...     ...
165  how did you die to that. seriously afk farming...      -1
166  nice deny. anyone needs courier? let's win thi...       1
167  you fucking noobs are useless. going solo with...      -1
168  care bot, we need more wards there. nice teamw...       1
169  stop playing dota if you can't even hold your ...      -1

[170 rows x 2 columns]

In [63]:
first = generated_df

In [75]:
combined = pd.concat([first, generated_df]).sample(n=1000)

In [78]:
combined.to_csv('../data/generated/dota2/privacy_protected/grouped_summary_stats_dota2_gen.csv', index=False)

In [ ]:
res = []
for i in range(100):
    response = client.responses.create(
        model="gpt-4o",
        instructions=instruction,
        input=input
    )
    res.append(response.output_text)

In [88]:
labels = []
sentences = []
for i in range(50):
    for word in res[i].split("\n"):
        match = re.match(r'"(.*?)"\s*(-?\d+)', word)
        if match:
            quoted = match.group(1)      
            label = match.group(2)       
            sentences.append(quoted)
            labels.append(int(label))

In [89]:
generated_df = pd.DataFrame({
    'sentences': sentences,
    'labels': labels
})

In [86]:
old_df = generated_df

In [91]:
generated_df = pd.concat([old_df, generated_df], axis=0)

In [92]:
generated_df.to_csv('../data/generated/dota2/privacy_protected/summary_stats_dota2_gen.csv', index=False)