In [135]:
import sys
sys.path.append('../utilities/')

In [136]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
import torch
from sentence_transformers import SentenceTransformer
from joblib import dump
from openai import OpenAI
from tqdm import tqdm
from mmd import MMD
import re
from sklearn.feature_extraction.text import CountVectorizer

In [212]:
orig_df = pd.read_csv('../data/initial_datasets/dota2/dota2_grouped_train.csv')
gen_df = pd.read_csv('../data/generated/dota2/token_co_occurences/grouped_gen_token_co_occurences_no_stop_words.csv')
gen_df = gen_df.sample(n=250, random_state=42)

In [138]:
orig_df = orig_df.rename(columns={'translated_message': 'sentences', 'label': 'labels'})
orig_df['labels'] = orig_df['labels'].fillna(0)
orig_df['labels'] = orig_df['labels'].replace({'x': 1})
orig_df['labels'] = orig_df['labels'].astype(int)
orig_df = orig_df[['sentences', 'labels']]

In [213]:
orig_df = orig_df.rename(columns={'translated_message': 'sentences', 'label': 'labels'})
gen_df = gen_df.rename(columns={'chat': 'sentences', 'label': 'labels'})
orig_df['labels'] = orig_df['labels'].replace({1: -1, 0: 1})

In [190]:
orig_df

     match  player                                          sentences  labels
0       33       1  "hp?". "first bash". haha. "Me too". "alright ...       1
1       76       5  "What the fuck". "what 2 suicides". "he left"....       1
2       28       3  xd. "easy mid". report lion carry. "easy oof"....      -1
3       77       2                                                 gg       1
4        4       8                        Well played.. "Well played"       1
..     ...     ...                                                ...     ...
245     41       1  "report invoker". "Feeding with the courier". ...      -1
246      8       5                                       Gg. 0-20. gg       1
247     54       3  "the moment the guy fell". "damn booster". "de...       1
248     10       9  "Who are you talking to?". "ha?" translates to...       1
249     89       5  "Go talk shit)". easy. "Got distracted by the ...      -1

[250 rows x 4 columns]

In [191]:
gen_df

                                             sentences labels
521  You ARE SUCH a fucking garbage player. REPORT ...   -1
737  How do you manage to screw up every game I’m w...   -1
740  GG everyone, nice match.Jungle is stacked if y...    1
660  What are you doing?This game is over if you ke...   -1
411  guys back off!they’re closing in.regroup high ...    1
..                                                 ...    ...
109  Can you stop feeding? It's like you learned no...     -1
430  That Eul's was on point!Let's focus Luna next....    1
77   Why the hell go jungle, you're useless. How ca...   -1
84   nice try team.we almost had that one.great pla...    1
286  you call this playing? quit trolling and get s...   -1

[250 rows x 2 columns]

# **Tools**

In [214]:
sentence_transformer = SentenceTransformer('all-mpnet-base-v2')

# **MMD**

In [215]:
X = np.array(sentence_transformer.encode(orig_df['sentences'].to_list()))
Y = np.array(sentence_transformer.encode(gen_df['sentences'].to_list()))

In [216]:
def report_MMD(X, Y, normalize=False):
    
    tensorX = torch.tensor(X)
    tensorY = torch.tensor(Y)
    rbf_mmd = MMD(tensorX, tensorY, "rbf")
    scale_mmd = MMD(tensorX, tensorY, "multiscale")


    if normalize:
        return (rbf_mmd.item() / np.sqrt((1.0 / X.shape[0]) + (1.0 / Y.shape[0]))), (scale_mmd.item() / np.sqrt(1.0 / X.shape[0] + 1.0 / Y.shape[0]))
    else:
        return rbf_mmd.item(), scale_mmd.item()

In [217]:
report_MMD(X, Y, normalize=True)

(np.float64(0.5043956362896207), np.float64(2.311948834365545))

In [218]:
import numpy as np
import ot

def wasserstein(X, Y):
    
    a = np.ones((X.shape[0],)) / X.shape[0]
    b = np.ones((Y.shape[0],)) / Y.shape[0]

    M = ot.dist(X, Y)
    M /= M.max()

    return ot.emd2(a, b, M)

In [219]:
wasserstein(X, Y)

0.5823215568065645

# **Classification**

## **Train on Synthetic Only**

In [220]:
train_df = gen_df
test_df = orig_df

train_df['labels'] = train_df['labels'].astype(int)
test_df['labels'] = test_df['labels'].astype(int)

X_train = train_df['sentences']
X_test = test_df['sentences']

y_train = train_df['labels']
y_test = test_df['labels']

In [221]:
train_df

                                             sentences  labels
521  You ARE SUCH a fucking garbage player. REPORT ...      -1
737  How do you manage to screw up every game I’m w...      -1
740  GG everyone, nice match.Jungle is stacked if y...       1
660  What are you doing?This game is over if you ke...      -1
411  guys back off!they’re closing in.regroup high ...       1
..                                                 ...     ...
109  Can you stop feeding? It's like you learned no...      -1
430  That Eul's was on point!Let's focus Luna next....       1
77   Why the hell go jungle, you're useless. How ca...      -1
84   nice try team.we almost had that one.great pla...       1
286  you call this playing? quit trolling and get s...      -1

[250 rows x 2 columns]

In [222]:
y_train

521   -1
737   -1
740    1
660   -1
411    1
      ..
109   -1
430    1
77    -1
84     1
286   -1
Name: labels, Length: 250, dtype: int64

In [223]:
X_train = np.array(sentence_transformer.encode(X_train.to_list()))
X_test = np.array(sentence_transformer.encode(X_test.to_list()))

In [224]:
model = svm.SVC(kernel='linear', probability=True, class_weight='balanced', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_train)
train_acc = accuracy_score(y_pred, y_train)
print(f'Train acc: {train_acc}')

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_pred, y_test)
print(f'Test acc: {test_acc}')

Train acc: 0.996
Test acc: 0.288

In [225]:
print(precision_score(y_test.to_list(), y_pred))
print(recall_score(y_test.to_list(), y_pred))

0.9782608695652174
0.20270270270270271

In [226]:
y_prob = model.predict_proba(X_test)[:, 1]
print(roc_auc_score(y_test, y_prob))

0.7302123552123552

# **Train on Synthetic + 100 Real**

In [227]:
orig_sample_df = pd.read_csv('../data/initial_datasets/dota2/dota2_grouped_test.csv')

In [228]:
orig_sample_df = orig_sample_df.drop(columns=['match', 'player'])
orig_sample_df = orig_sample_df.rename(columns={'translated_message': 'sentences', 'label': 'labels'})
orig_sample_df['labels'] = orig_sample_df['labels'].replace({1: -1, 0: 1})

In [229]:
train_df = pd.concat([gen_df.sample(frac=0.9, random_state=42), orig_sample_df.sample(frac=0.1, random_state=42)]).sample(frac=1, random_state=42).reset_index(drop=True)
test_df = orig_df.sample(frac=1, random_state=42).reset_index(drop=True)

X_train = train_df['sentences']
X_test = test_df['sentences']

y_train = train_df['labels']
y_test = test_df['labels']

In [230]:
X_train = np.array(sentence_transformer.encode(X_train.to_list()))
X_test = np.array(sentence_transformer.encode(X_test.to_list()))

In [231]:
model = svm.SVC(kernel='linear', probability=True, class_weight='balanced', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_train)
train_acc = accuracy_score(y_pred, y_train)
print(f'Train acc: {train_acc}')

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_pred, y_test)
print(f'Test acc: {test_acc}')

Train acc: 0.984
Test acc: 0.7

In [232]:
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))

0.9622641509433962
0.6891891891891891

In [233]:
y_prob = model.predict_proba(X_test)[:, 1]
print(roc_auc_score(y_test, y_prob))

0.7787966537966539

# **Wasserstein**

In [ ]:
import numpy as np
import ot

def wasserstein(X, Y):
    
    a = np.ones((X.shape[0],)) / X.shape[0]
    b = np.ones((Y.shape[0],)) / Y.shape[0]

    M = ot.dist(X, Y)
    M /= M.max()

    return ot.emd2(a, b, M)

In [ ]:
gen_df

                          sentences  labels
0         gg ez noobs learn to play       0
1       nice play team, keep it up!       1
2        fucking idiot stop feeding       0
3    good fight, let's keep pushing       1
4         report this faggot feeder       0
..                              ...     ...
995         stop feeding you retard       0
996   gg wp guys, let's queue again       1
997           bunch of noob bitches       0
998        easy game, good teamwork       1
999         you're trash, no skill!       0

[1000 rows x 2 columns]

In [ ]:
orig_d

,message,label,player,special_token_message,match,translated_message,sanitized_translated_message
986,mk,NaN,2,[Team0][Player2]: mk,33,mk,mk
2898,trip,NaN,4,[Team0][Player4]: trip,64,trip,trip
3315,))),NaN,9,[Team1][Player4]: ))),82,))),)))
1720,QUE PEGA ISSO,NaN,5,[Team1][Player0]: QUE PEGA ISSO,42,"""WHAT'S UP WITH THAT""",WHAT'S UP WITH THAT
552,вот и думай мусорка на морте,NaN,2,[Team0][Player2]: вот и думай мусорка на морте,30,"""there you go, think about it, trash on Mortred""","there you go, think about it, **** on Mortred"
...,...,...,...,...,...,...,...
78,x3 gem,NaN,9,[Team1][Player4]: x3 gem,13,"""x3 gem""",x3 gem
1680,gg,NaN,5,[Team1][Player0]: gg,84,gg,gg
2369,gg,NaN,2,[Team0][Player2]: gg,80,gg,gg
1442,i also kill,NaN,1,[Team0][Player1]: i also kill,43,"""i also kill""",i also kill
2352,pa,NaN,3,[Team0][Player3]: pa,80,"""bro""",bro

In [ ]:
X = np.array(sentence_transformer.encode(orig_df['translated_message'].to_list()))
Y = np.array(sentence_transformer.encode(gen_df['sentences'].to_list()))

In [ ]:
wasserstein(X, Y)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

0.5516760837584738

# **Classifier**

In [ ]:
orig_df

               sentences  labels      type
3094           "come on"       0  original
1046             RAMPAGE       0  original
214        "fucking lag"       0  original
1971  "your mom, idiot?"       0  original
1973           "nothing"       0  original
...                  ...     ...       ...
179             snipshit       0  original
603                   Gg       0  original
294                 game       0  original
2813     "well at least"       0  original
2398                sCCC       0  original

[1000 rows x 3 columns]

In [ ]:
gen_df

                          sentences  labels       type
0         gg ez noobs learn to play       0  synthetic
1       nice play team, keep it up!       1  synthetic
2        fucking idiot stop feeding       0  synthetic
3    good fight, let's keep pushing       1  synthetic
4         report this faggot feeder       0  synthetic
..                              ...     ...        ...
995         stop feeding you retard       0  synthetic
996   gg wp guys, let's queue again       1  synthetic
997           bunch of noob bitches       0  synthetic
998        easy game, good teamwork       1  synthetic
999         you're trash, no skill!       0  synthetic

[1000 rows x 3 columns]