In [50]:
import sys
sys.path.append('../utilities/')

In [51]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
import torch
from sentence_transformers import SentenceTransformer
from joblib import dump
from openai import OpenAI
from tqdm import tqdm
from mmd import MMD
import re
from sklearn.feature_extraction.text import CountVectorizer

In [52]:
orig_df = pd.read_csv('../data/initial_datasets/dota2/dota2_grouped_train.csv')
gen_df = pd.read_csv('../data/generated/dota2/conversational_generations/grouped_conversational_var_len.csv')
gen_df = gen_df.sample(n=250, random_state=42)

In [15]:
orig_df['labels'].value_counts()

labels
0    222
1     28
Name: count, dtype: int64

In [13]:
orig_df['sentences'].iloc[1]

'"What the fuck". "what 2 suicides". "he left". read chat. gg. gg'

In [53]:
gen_df

                                   translated_messages  label
142  "ur ass". "team trash". "aim ass". "noob team"...      0
6    "ez bot". "stfu trash". "aim bot??". "git rekt...      0
97   "lol noob". "haha lucky". "whatever". "not ur ...      0
60   "u ass!". "this team sux". "play better". "u r...      0
112  "ur bot". "git gud". "stfu loser". "like trash...      0
..                                                 ...    ...
106  "u r trash". "ass aim". "same strat?". "bad mo...      0
14   "need help?". "ok np". "glhf :)". "nice try". ...      1
92   "Need help". "Im revving". "On ur six". "Push ...      1
179  "u wish". "dont care". "ur trash". "ass yourse...      0
102  "need help?". "gg team". "nice shot". "cover m...      1

[250 rows x 2 columns]

In [54]:
orig_df = orig_df.rename(columns={'translated_message': 'sentences', 'label': 'labels'})
orig_df['labels'] = orig_df['labels'].fillna(0)
orig_df['labels'] = orig_df['labels'].replace({'x': 1})
orig_df['labels'] = orig_df['labels'].astype(int)
orig_df = orig_df[['sentences', 'labels']]

In [55]:
orig_df = orig_df.rename(columns={'translated_message': 'sentences', 'label': 'labels'})
gen_df = gen_df.rename(columns={'translated_messages': 'sentences', 'label': 'labels'})
orig_df['labels'] = orig_df['labels'].replace({1: 0, 0: 1})

In [17]:
orig_df

                                             sentences  labels
0    "hp?". "first bash". haha. "Me too". "alright ...       1
1    "What the fuck". "what 2 suicides". "he left"....       1
2    xd. "easy mid". report lion carry. "easy oof"....       0
3                                                   gg       1
4                          Well played.. "Well played"       1
..                                                 ...     ...
245  "report invoker". "Feeding with the courier". ...       0
246                                       Gg. 0-20. gg       1
247  "the moment the guy fell". "damn booster". "de...       1
248  "Who are you talking to?". "ha?" translates to...       1
249  "Go talk shit)". easy. "Got distracted by the ...       0

[250 rows x 2 columns]

In [18]:
gen_df

                                             sentences  labels
142  "thx 4 cover". "lol nice shot". "need help?". ...       1
6    "stfu noob". "lmao git gud". "team trash". "st...       0
97   "you wish". "dont care". "like urself". "nah u...       0
60   "gg wp". "need help?". "gj team". "stay safe"....       1
112  "Need cover". "Sniper up!". "I’m on it". "Just...       1
..                                                 ...     ...
106  "Follow me". "Need backup". "Nice shot". "Just...       1
14   "Need ammo?". "Haha, okay". "Nice shot!". "Sor...       1
92   "need help?". "i'm here". "cover u". "drop amm...       1
179  "git gud". "u'r bad". "lmao u wish". "nah ass"...       0
102  "noob team". "ez gg". "trash player". "stop ca...       0

[250 rows x 2 columns]

# **Tools**

In [56]:
sentence_transformer = SentenceTransformer('all-mpnet-base-v2')

# **MMD**

In [57]:
X = np.array(sentence_transformer.encode(orig_df['sentences'].to_list()))
Y = np.array(sentence_transformer.encode(gen_df['sentences'].to_list()))

In [58]:
def report_MMD(X, Y, normalize=False):
    
    tensorX = torch.tensor(X)
    tensorY = torch.tensor(Y)
    rbf_mmd = MMD(tensorX, tensorY, "rbf")
    scale_mmd = MMD(tensorX, tensorY, "multiscale")


    if normalize:
        return (rbf_mmd.item() / np.sqrt((1.0 / X.shape[0]) + (1.0 / Y.shape[0]))), (scale_mmd.item() / np.sqrt(1.0 / X.shape[0] + 1.0 / Y.shape[0]))
    else:
        return rbf_mmd.item(), scale_mmd.item()

In [59]:
report_MMD(X, Y, normalize=True)

(np.float64(0.6362309181757031), np.float64(4.3649718742936585))

In [60]:
import numpy as np
import ot

def wasserstein(X, Y):
    
    a = np.ones((X.shape[0],)) / X.shape[0]
    b = np.ones((Y.shape[0],)) / Y.shape[0]

    M = ot.dist(X, Y)
    M /= M.max()

    return ot.emd2(a, b, M)

In [61]:
wasserstein(X, Y)

0.5355231311321258

# **Classification**

## **Train on Synthetic Only**

In [62]:
train_df = gen_df
test_df = orig_df

train_df['labels'] = train_df['labels'].astype(int)
test_df['labels'] = test_df['labels'].astype(int)

X_train = train_df['sentences']
X_test = test_df['sentences']

y_train = train_df['labels']
y_test = test_df['labels']

In [26]:
train_df

                                             sentences  labels
142  "thx 4 cover". "lol nice shot". "need help?". ...       1
6    "stfu noob". "lmao git gud". "team trash". "st...       0
97   "you wish". "dont care". "like urself". "nah u...       0
60   "gg wp". "need help?". "gj team". "stay safe"....       1
112  "Need cover". "Sniper up!". "I’m on it". "Just...       1
..                                                 ...     ...
106  "Follow me". "Need backup". "Nice shot". "Just...       1
14   "Need ammo?". "Haha, okay". "Nice shot!". "Sor...       1
92   "need help?". "i'm here". "cover u". "drop amm...       1
179  "git gud". "u'r bad". "lmao u wish". "nah ass"...       0
102  "noob team". "ez gg". "trash player". "stop ca...       0

[250 rows x 2 columns]

In [27]:
y_train

142    1
6      0
97     0
60     1
112    1
      ..
106    1
14     1
92     1
179    0
102    0
Name: labels, Length: 250, dtype: int64

In [63]:
X_train = np.array(sentence_transformer.encode(X_train.to_list()))
X_test = np.array(sentence_transformer.encode(X_test.to_list()))

In [64]:
model = svm.SVC(kernel='linear', probability=True, class_weight='balanced', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_train)
train_acc = accuracy_score(y_pred, y_train)
print(f'Train acc: {train_acc}')

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_pred, y_test)
print(f'Test acc: {test_acc}')

Train acc: 0.948
Test acc: 0.676

In [65]:
print(precision_score(y_test.to_list(), y_pred))
print(recall_score(y_test.to_list(), y_pred))

0.9122807017543859
0.7027027027027027

In [66]:
y_prob = model.predict_proba(X_test)[:, 1]
print(roc_auc_score(y_test, y_prob))

0.6325611325611326

# **Train on Synthetic + 100 Real**

In [67]:
orig_sample_df = pd.read_csv('../data/initial_datasets/dota2/dota2_grouped_test.csv')

In [68]:
orig_sample_df = orig_sample_df.drop(columns=['match', 'player'])
orig_sample_df = orig_sample_df.rename(columns={'translated_message': 'sentences', 'label': 'labels'})
orig_sample_df['labels'] = orig_sample_df['labels'].replace({1: 0, 0: 1})

In [69]:
train_df = pd.concat([gen_df.sample(frac=0.9, random_state=42), orig_sample_df.sample(frac=0.1, random_state=42)]).sample(frac=1, random_state=42).reset_index(drop=True)
test_df = orig_df.sample(frac=1, random_state=42).reset_index(drop=True)

X_train = train_df['sentences']
X_test = test_df['sentences']

y_train = train_df['labels']
y_test = test_df['labels']

In [70]:
X_train = np.array(sentence_transformer.encode(X_train.to_list()))
X_test = np.array(sentence_transformer.encode(X_test.to_list()))

In [71]:
model = svm.SVC(kernel='linear', probability=True, class_weight='balanced', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_train)
train_acc = accuracy_score(y_pred, y_train)
print(f'Train acc: {train_acc}')

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_pred, y_test)
print(f'Test acc: {test_acc}')

Train acc: 0.932
Test acc: 0.84

In [72]:
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))

0.90625
0.9144144144144144

In [73]:
y_prob = model.predict_proba(X_test)[:, 1]
print(roc_auc_score(y_test, y_prob))

0.7104247104247104

# **Wasserstein**

In [ ]:
import numpy as np
import ot

def wasserstein(X, Y):
    
    a = np.ones((X.shape[0],)) / X.shape[0]
    b = np.ones((Y.shape[0],)) / Y.shape[0]

    M = ot.dist(X, Y)
    M /= M.max()

    return ot.emd2(a, b, M)

In [ ]:
gen_df

                          sentences  labels
0         gg ez noobs learn to play       0
1       nice play team, keep it up!       1
2        fucking idiot stop feeding       0
3    good fight, let's keep pushing       1
4         report this faggot feeder       0
..                              ...     ...
995         stop feeding you retard       0
996   gg wp guys, let's queue again       1
997           bunch of noob bitches       0
998        easy game, good teamwork       1
999         you're trash, no skill!       0

[1000 rows x 2 columns]

In [ ]:
orig_d

,message,label,player,special_token_message,match,translated_message,sanitized_translated_message
986,mk,NaN,2,[Team0][Player2]: mk,33,mk,mk
2898,trip,NaN,4,[Team0][Player4]: trip,64,trip,trip
3315,))),NaN,9,[Team1][Player4]: ))),82,))),)))
1720,QUE PEGA ISSO,NaN,5,[Team1][Player0]: QUE PEGA ISSO,42,"""WHAT'S UP WITH THAT""",WHAT'S UP WITH THAT
552,вот и думай мусорка на морте,NaN,2,[Team0][Player2]: вот и думай мусорка на морте,30,"""there you go, think about it, trash on Mortred""","there you go, think about it, **** on Mortred"
...,...,...,...,...,...,...,...
78,x3 gem,NaN,9,[Team1][Player4]: x3 gem,13,"""x3 gem""",x3 gem
1680,gg,NaN,5,[Team1][Player0]: gg,84,gg,gg
2369,gg,NaN,2,[Team0][Player2]: gg,80,gg,gg
1442,i also kill,NaN,1,[Team0][Player1]: i also kill,43,"""i also kill""",i also kill
2352,pa,NaN,3,[Team0][Player3]: pa,80,"""bro""",bro

In [ ]:
X = np.array(sentence_transformer.encode(orig_df['translated_message'].to_list()))
Y = np.array(sentence_transformer.encode(gen_df['sentences'].to_list()))

In [ ]:
wasserstein(X, Y)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

0.5516760837584738

# **Classifier**

In [ ]:
orig_df

               sentences  labels      type
3094           "come on"       0  original
1046             RAMPAGE       0  original
214        "fucking lag"       0  original
1971  "your mom, idiot?"       0  original
1973           "nothing"       0  original
...                  ...     ...       ...
179             snipshit       0  original
603                   Gg       0  original
294                 game       0  original
2813     "well at least"       0  original
2398                sCCC       0  original

[1000 rows x 3 columns]

In [ ]:
gen_df

                          sentences  labels       type
0         gg ez noobs learn to play       0  synthetic
1       nice play team, keep it up!       1  synthetic
2        fucking idiot stop feeding       0  synthetic
3    good fight, let's keep pushing       1  synthetic
4         report this faggot feeder       0  synthetic
..                              ...     ...        ...
995         stop feeding you retard       0  synthetic
996   gg wp guys, let's queue again       1  synthetic
997           bunch of noob bitches       0  synthetic
998        easy game, good teamwork       1  synthetic
999         you're trash, no skill!       0  synthetic

[1000 rows x 3 columns]