In [132]:
import sys
sys.path.append('../utilities/')

In [133]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
import torch
from sentence_transformers import SentenceTransformer
from joblib import dump
from openai import OpenAI
from tqdm import tqdm
from mmd import MMD
import re
from sklearn.feature_extraction.text import CountVectorizer

In [46]:
gen_df = pd.read_csv('../data/generated/dota2/conversational_generations/grouped_conversational_var_len.csv')

In [48]:
gen_df['label'] = gen_df['label'].replace({1: 0, 0: 1})

In [58]:
path = '../data/generated/dota2/token_co_occurences/grouped_gen_token_co_occurences_no_stop_words.csv'

gen_df = pd.read_csv(path)
gen_df

                                             sentences labels
0    ward the jungle please.anyone needs courier be...    1
1    wasting my time with you idiots."If I would" k...   -1
2    Why are you playing like a potato? Get it toge...   -1
3    that was close, good defense team. we can turn...    1
4    Let's coordinate the ganks.If we win the next ...    1
..                                                 ...    ...
995  Good luck have fun everyone. Remember to ward ...    1
996  Don’t forget to farm the jungle safely. I’ll s...    1
997  "I can't believe we lost that."You guys are th...   -1
998  mid needs help.go stop feeding.noob, you're th...   -1
999  Careful top lane, they’re missing from mid. I’...    1

[1000 rows x 2 columns]

In [89]:
gen_df.to_csv(path, index=False)

In [59]:
col_name = 'labels'
gen_df[col_name] = gen_df[col_name].replace({1: 0, -1: 1})
gen_df.to_csv(path, index=False)

In [134]:
orig_df = pd.read_csv('../data/initial_datasets/dota2/dota2_grouped_test.csv')
gen_df = pd.read_csv('../data/generated/dota2/privacy_protected/grouped_summary_stats_dota2_gen.csv')
gen_df = gen_df.sample(n=250, random_state=42)

In [135]:
gen_df

                                              messages  labels
521  why you pick carry if you can't play? noob af....       1
737  this tidehunter is a joke. can't even land a r...       1
740  just quit the game, you're so bad. fucking noo...       1
660  wtf are you doing sf. stop feeding you noob. l...       1
411  drow, awesome silence. good save. we can push ...       0
..                                                 ...     ...
109  you're a fking idiot, stop feeding mid. report...       1
430  focus on objective and push. nice stuns, lion....       0
77   gg team well played. Let's push mid. Care bot,...       0
84   nice gank mid, guys. care top, they're rotatin...       0
286  fucking idiots everywhere, no wards no ganks. ...       1

[250 rows x 2 columns]

In [136]:
orig_df

     match  player                                           messages  labels
0       83       4                                         end please       0
1       22       0  "TERROR". "HOW DID YOU FARM?". "COMPLETELY EAS...       1
2        5       5  _. lol. bad computer. "noob". "Easy". EZ. "E...       0
3       92       5                          no. "Am I to blame?". lol       0
4       40       5  "send the channel ". "or on Twitch?". "shut t...       1
..     ...     ...                                                ...     ...
245     23       1                   I'm buying this Assault Cuirass.       0
246     87       3                                       REPORT NOOBS       0
247     12       2                                               easy       0
248     58       9  It's like 4% to get two bashes in a row.. and ...       0
249     13       6                                                 gg       0

[250 rows x 4 columns]

In [16]:
orig_df = orig_df.rename(columns={'translated_message': 'sentences', 'label': 'labels'})
orig_df['labels'] = orig_df['labels'].fillna(0)
orig_df['labels'] = orig_df['labels'].replace({'x': 1})
orig_df['labels'] = orig_df['labels'].astype(int)
orig_df = orig_df[['sentences', 'labels']]

In [23]:
orig_df = orig_df.rename(columns={'translated_message': 'sentences', 'label': 'labels'})
gen_df = gen_df.rename(columns={'translated_messages': 'sentences', 'label': 'labels'})

In [24]:
orig_df

                                             sentences  labels
0                                           end please       0
1    "TERROR". "HOW DID YOU FARM?". "COMPLETELY EAS...       1
2    _. lol. bad computer. "noob". "Easy". EZ. "E...       0
3                            no. "Am I to blame?". lol       0
4    "send the channel ". "or on Twitch?". "shut t...       1
..                                                 ...     ...
245                   I'm buying this Assault Cuirass.       0
246                                       REPORT NOOBS       0
247                                               easy       0
248  It's like 4% to get two bashes in a row.. and ...       0
249                                                 gg       0

[250 rows x 2 columns]

In [25]:
gen_df

                                             sentences  labels
142  "omg y tf u campin?? n00b". "ur so bad srsly s...       1
6    "omg n00b y u even in this lobby!!!". "pls i g...       1
97   "wtf are u noobs doing, move it!!". "ffs cant ...       1
60   "omg ur such a noob omg". "im wrecking u n u c...       1
112  "omg u noob learn2play". "ur trash kid, uninst...       1
..                                                 ...     ...
106  "omw to obj, cover me!". "thx! nade out". "sry...       0
14   "hey team, let's go for the objctv!". "haha, j...       0
92   "omg ur such a n00b!!!". "try hrdrrr!! we’re l...       1
179  "nah, lets camp and rack up kills like a boss"...       1
102  "omg ur so bad lmao 😂". "nah u just mad cuz u ...       1

[250 rows x 2 columns]

# **Tools**

In [137]:
sentence_transformer = SentenceTransformer('all-mpnet-base-v2')

# **MMD**

In [138]:
X = np.array(sentence_transformer.encode(orig_df['messages'].to_list()))
Y = np.array(sentence_transformer.encode(gen_df['messages'].to_list()))

In [139]:
def report_MMD(X, Y, normalize=False):
    
    tensorX = torch.tensor(X)
    tensorY = torch.tensor(Y)
    rbf_mmd = MMD(tensorX, tensorY, "rbf")
    scale_mmd = MMD(tensorX, tensorY, "multiscale")


    if normalize:
        return (rbf_mmd.item() / np.sqrt((1.0 / X.shape[0]) + (1.0 / Y.shape[0]))), (scale_mmd.item() / np.sqrt(1.0 / X.shape[0] + 1.0 / Y.shape[0]))
    else:
        return rbf_mmd.item(), scale_mmd.item()

In [140]:
report_MMD(X, Y, normalize=True)

(np.float64(0.6233880537629256), np.float64(3.137966527529445))

In [141]:
import numpy as np
import ot

def wasserstein(X, Y):
    
    a = np.ones((X.shape[0],)) / X.shape[0]
    b = np.ones((Y.shape[0],)) / Y.shape[0]

    M = ot.dist(X, Y)
    M /= M.max()

    return ot.emd2(a, b, M)

In [142]:
wasserstein(X, Y)

0.5812677550911901

# **Classification**

## **Train on Synthetic Only**

In [146]:
train_df = gen_df
test_df = orig_df

train_df['labels'] = train_df['labels'].astype(int)
test_df['labels'] = test_df['labels'].astype(int)

X_train = train_df['messages']
X_test = test_df['messages']

y_train = train_df['labels']
y_test = test_df['labels']

In [147]:
train_df

                                              messages  labels
521  why you pick carry if you can't play? noob af....       1
737  this tidehunter is a joke. can't even land a r...       1
740  just quit the game, you're so bad. fucking noo...       1
660  wtf are you doing sf. stop feeding you noob. l...       1
411  drow, awesome silence. good save. we can push ...       0
..                                                 ...     ...
109  you're a fking idiot, stop feeding mid. report...       1
430  focus on objective and push. nice stuns, lion....       0
77   gg team well played. Let's push mid. Care bot,...       0
84   nice gank mid, guys. care top, they're rotatin...       0
286  fucking idiots everywhere, no wards no ganks. ...       1

[250 rows x 2 columns]

In [148]:
y_train

521    1
737    1
740    1
660    1
411    0
      ..
109    1
430    0
77     0
84     0
286    1
Name: labels, Length: 250, dtype: int64

In [149]:
X_train = np.array(sentence_transformer.encode(X_train.to_list()))
X_test = np.array(sentence_transformer.encode(X_test.to_list()))

In [150]:
model = svm.SVC(kernel='linear', probability=True, class_weight='balanced', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_train)
train_acc = accuracy_score(y_pred, y_train)
print(f'Train acc: {train_acc}')

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_pred, y_test)
print(f'Test acc: {test_acc}')

Train acc: 1.0
Test acc: 0.564

In [151]:
print(precision_score(y_test.to_list(), y_pred))
print(recall_score(y_test.to_list(), y_pred))

0.23943661971830985
0.9714285714285714

In [152]:
y_prob = model.predict_proba(X_test)[:, 1]
print(roc_auc_score(y_test, y_prob))

0.8194019933554817

# **Train on Synthetic + 100 Real**

In [153]:
orig_sample_df = pd.read_csv('../data/initial_datasets/dota2/dota2_grouped_test.csv')

In [ ]:
orig_sample_df = orig_sample_df.drop(columns=['match', 'player'])
orig_sample_df = orig_sample_df.rename(columns={'translated_message': 'sentences', 'label': 'labels'})

In [154]:
train_df = pd.concat([gen_df.sample(frac=0.9, random_state=42), orig_sample_df.sample(frac=0.1, random_state=42)]).sample(frac=1, random_state=42).reset_index(drop=True)
test_df = orig_df.sample(frac=1, random_state=42).reset_index(drop=True)

X_train = train_df['messages']
X_test = test_df['messages']

y_train = train_df['labels']
y_test = test_df['labels']

In [155]:
X_train = np.array(sentence_transformer.encode(X_train.to_list()))
X_test = np.array(sentence_transformer.encode(X_test.to_list()))

In [129]:
model = svm.SVC(kernel='linear', probability=True, class_weight='balanced', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_train)
train_acc = accuracy_score(y_pred, y_train)
print(f'Train acc: {train_acc}')

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_pred, y_test)
print(f'Test acc: {test_acc}')

Train acc: 0.932
Test acc: 0.868

In [156]:
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))

0.1267605633802817
0.5142857142857142

In [157]:
y_prob = model.predict_proba(X_test)[:, 1]
print(roc_auc_score(y_test, y_prob))

0.8194019933554817

# **Wasserstein**

In [ ]:
import numpy as np
import ot

def wasserstein(X, Y):
    
    a = np.ones((X.shape[0],)) / X.shape[0]
    b = np.ones((Y.shape[0],)) / Y.shape[0]

    M = ot.dist(X, Y)
    M /= M.max()

    return ot.emd2(a, b, M)

In [ ]:
gen_df

                          sentences  labels
0         gg ez noobs learn to play       0
1       nice play team, keep it up!       1
2        fucking idiot stop feeding       0
3    good fight, let's keep pushing       1
4         report this faggot feeder       0
..                              ...     ...
995         stop feeding you retard       0
996   gg wp guys, let's queue again       1
997           bunch of noob bitches       0
998        easy game, good teamwork       1
999         you're trash, no skill!       0

[1000 rows x 2 columns]

In [ ]:
orig_d

,message,label,player,special_token_message,match,translated_message,sanitized_translated_message
986,mk,NaN,2,[Team0][Player2]: mk,33,mk,mk
2898,trip,NaN,4,[Team0][Player4]: trip,64,trip,trip
3315,))),NaN,9,[Team1][Player4]: ))),82,))),)))
1720,QUE PEGA ISSO,NaN,5,[Team1][Player0]: QUE PEGA ISSO,42,"""WHAT'S UP WITH THAT""",WHAT'S UP WITH THAT
552,вот и думай мусорка на морте,NaN,2,[Team0][Player2]: вот и думай мусорка на морте,30,"""there you go, think about it, trash on Mortred""","there you go, think about it, **** on Mortred"
...,...,...,...,...,...,...,...
78,x3 gem,NaN,9,[Team1][Player4]: x3 gem,13,"""x3 gem""",x3 gem
1680,gg,NaN,5,[Team1][Player0]: gg,84,gg,gg
2369,gg,NaN,2,[Team0][Player2]: gg,80,gg,gg
1442,i also kill,NaN,1,[Team0][Player1]: i also kill,43,"""i also kill""",i also kill
2352,pa,NaN,3,[Team0][Player3]: pa,80,"""bro""",bro

In [ ]:
X = np.array(sentence_transformer.encode(orig_df['translated_message'].to_list()))
Y = np.array(sentence_transformer.encode(gen_df['sentences'].to_list()))

In [ ]:
wasserstein(X, Y)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

0.5516760837584738

# **Classifier**

In [ ]:
orig_df

               sentences  labels      type
3094           "come on"       0  original
1046             RAMPAGE       0  original
214        "fucking lag"       0  original
1971  "your mom, idiot?"       0  original
1973           "nothing"       0  original
...                  ...     ...       ...
179             snipshit       0  original
603                   Gg       0  original
294                 game       0  original
2813     "well at least"       0  original
2398                sCCC       0  original

[1000 rows x 3 columns]

In [ ]:
gen_df

                          sentences  labels       type
0         gg ez noobs learn to play       0  synthetic
1       nice play team, keep it up!       1  synthetic
2        fucking idiot stop feeding       0  synthetic
3    good fight, let's keep pushing       1  synthetic
4         report this faggot feeder       0  synthetic
..                              ...     ...        ...
995         stop feeding you retard       0  synthetic
996   gg wp guys, let's queue again       1  synthetic
997           bunch of noob bitches       0  synthetic
998        easy game, good teamwork       1  synthetic
999         you're trash, no skill!       0  synthetic

[1000 rows x 3 columns]