In [25]:
import sys
sys.path.append('../utilities/')
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
import torch
from sentence_transformers import SentenceTransformer
from joblib import dump
from openai import OpenAI
from tqdm import tqdm
from mmd import MMD
import re
from sklearn.feature_extraction.text import CountVectorizer
import tiktoken
from collections import defaultdict, Counter
import os
from dotenv import load_dotenv

# **Sentence Transformer**

In [2]:
sentence_transformer = SentenceTransformer('all-mpnet-base-v2')

# **Data Pre-processing**

In [3]:
train_df = pd.read_csv('../data/initial_datasets/reddit/reddit_train.csv')
test_df = pd.read_csv('../data/initial_datasets/reddit/reddit_test.csv')

In [4]:
train_df = train_df.sample(n=1000)

# **Tokenizer**

In [5]:
encoding = tiktoken.encoding_for_model("gpt-4")

# **LLM**

In [26]:
load_dotenv()
API_KEY = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=API_KEY)

# **Get Co-Occurences**

In [9]:
text = train_df['text'].to_list()

In [10]:
tokens_list = []
for sentence in text:
    token_ids = encoding.encode(sentence)
    # Optionally, get string versions of tokens
    tokens = [encoding.decode([tid]) for tid in token_ids]
    tokens_list.append(tokens)

In [12]:
cooc = defaultdict(Counter)

for tokens in tokens_list:
    unique_tokens = set(tokens)
    for token in unique_tokens:
        for other_token in unique_tokens:
            if token != other_token:
                cooc[token][other_token] += 1

In [19]:
top_k = 3

summary_text = ""
for token, counter in cooc.items():
    top = [w for w, _ in counter.most_common(top_k)]
    summary_text += f"'{token}' often appears with: {', '.join(top)}.\n"

In [20]:
print(summary_text)

' the' often appears with: ., ,,  I.
' you' often appears with: ., ,,  the.
',' often appears with: .,  the,  I.
' glad' often appears with:  I, ., ,.
' a' often appears with: .,  the, ,.
' I' often appears with: .,  the, ,.
' could' often appears with: .,  I,  that.
'’t' often appears with: ., ,,  the.
' fantastic' often appears with:  the,  you, ,.
' don' often appears with: ., 't,  the.
' and' often appears with: .,  the,  a.
' Have' often appears with:  a, .,  the.
'Well' often appears with: ., ,,  I.
' str' often appears with:  the,  you, ,.
'.' often appears with:  the,  I,  a.
'a' often appears with:  the,  I, I.
' scare' often appears with:  the,  you, ,.
' day' often appears with: .,  the,  a.
'ights' often appears with:  the,  you, ,.
'!' often appears with: .,  I,  the.
' let' often appears with: .,  the,  a.
' help' often appears with: .,  I,  the.
' away' often appears with:  the, .,  is.
' ' often appears with: ., ,,  the.
'50' often appears with:  the,  ,  I.
' so' often appears with: .,  I, ,.
'us' often appears with:  you,  ,  and.
' been' often appears with: ., ,,  I.
' seeing' often appears with:  I, .,  the.
' did' often appears with: .,  I,  you.
' how' often appears with: .,  the,  you.
' take' often appears with: .,  you,  this.
' improvement' often appears with:  the,  you,  .
'/ml' often appears with:  the,  you,  .
' any' often appears with: .,  of,  and.
' it' often appears with: .,  I,  the.
' are' often appears with: .,  the,  I.
' far' often appears with:  I,  and, ..
' taking' often appears with: .,  to,  the.
' to' often appears with: .,  the,  I.
' trying' often appears with:  to, .,  the.
' Lazar' often appears with:  the,  you,  .
' obvious' often appears with:  the,  I, 've.
''ve' often appears with: .,  I,  the.
' Not' often appears with: .,  the,  it.
' long' often appears with: .,  to,  the.
'?' often appears with: .,  the,  I.
'What' often appears with:  a, ., ?.
' dose' often appears with:  the,  you,  .
'mg' often appears with:  I,  so, ..
' dead' often appears with:  you, id, Are.
'id' often appears with:  dead,  you, Are.
'Are' often appears with:  you,  dead, id.
'iot' often appears with:  dead,  you, id.
'.....' often appears with:  you,  that,  dead.
' brain' often appears with: .,  it,  to.
'!!!' often appears with:  you,  that,  it.
' really' often appears with: ., ,,  the.
' that' often appears with: .,  the,  I.
' on' often appears with: .,  the,  I.
' piss' often appears with: .,  off,  on.
' Fuck' often appears with:  on,  piss,  this.
' this' often appears with: .,  I, I.
' their' often appears with: .,  the,  is.
'I' often appears with: .,  the,  I.
' right' often appears with: .,  to,  the.
' floor' often appears with:  on, .,  piss.
''d' often appears with: ., I,  a.
' deserve' often appears with: You,  come,  better.
' come' often appears with: .,  to,  the.
' better' often appears with: ., ,,  I.
'You' often appears with: .,  you, ,.
' things' often appears with: ., ,,  of.
' in' often appears with: .,  the,  a.
' there' often appears with: .,  the,  I.
' Hang' often appears with: You,  in,  there.
' will' often appears with: .,  and, NAME.
' Good' often appears with: .,  luck,  me.
' welcome' often appears with: ’re, You,  the.
'’re' often appears with: ., ’s,  and.
' if' often appears with: .,  it,  the.
' overflow' often appears with: ,,  ,  a.
' levels' often appears with: ,,  ,  a.
' bug' often appears with: ,,  ,  a.
' horrifying' often appears with: ,,  ,  a.
'It' often appears with: .,  the, 's.
' aggression' often appears with: ,,  ,  a.
' tried' often appears with: ., ,,  a.
' our' often appears with: .,  to,  a.
' an' often appears with: ., ,,  I.
' probably' often appears with: .,  a,  you.
' when' often appears with: .,  the, I.
' causes' often appears with: ,,  ,  a.
' we' often appears with: ., ,,  the.
' resets' often appears with: ,,  ,  a.
' be' often appears with: .,  to, ,.
' integer' often appears with: ,,  ,  a.
' would' often appears with: .,  the, ,.
' sad' often appears with: .,  I,  the.
'est' often appears with: .,  the,  I.
' my' often appears with: .,  I,  the.
' Hard' often appears with:  this, .,  sad.
' try' often appears with:  to, .,  for.
'nd' often appears with:  to, 2,  my.
' me' often appears with: .,  the,  to.
' got' often appears with: .,  I,  the.
' dam' often appears with:  sad,  I, est.
' guy' often appears with: .,  to, I.
' these' often appears with: ., I,  to.
' with' often appears with: .,  the,  to.
' days' often appears with:  I, I,  my.
'....' often appears with:  to,  the,  this.
' enough' often appears with:  to,  is,  the.
' not' often appears with: ., ,,  the.
' hate' often appears with: I,  I,  the.
' Bowl' often appears with:  the, ....,  to.
' was' often appears with: .,  the,  I.
' young' often appears with:  to, I,  that.
' remember' often appears with:  I,  this,  was.
' next' often appears with: ,,  the,  I.
' Super' often appears with:  was,  the, .....
' old' often appears with: .,  the,  I.
' but' often appears with: ., ,,  I.
'aaa' often appears with:  Been,  the,  a.
' Been' often appears with: ., aaa,  the.
' had' often appears with: .,  the,  a.
' just' often appears with: .,  the,  I.
'aaaa' often appears with: aaa,  Been,  the.
' looked' often appears with:  the,  a, ..
' kid' often appears with: .,  a,  I.
' little' often appears with: .,  a,  I.
'NAME' often appears with:  [, ], ..
' do' often appears with: .,  I,  the.
' handshake' often appears with: aaa,  Been,  the.
' confused' often appears with:  the,  a, ..
']' often appears with: NAME,  [, ..
'ah' often appears with:  I,  a, ..
' [' often appears with: NAME, ], ..
'H' often appears with:  I, .,  a.
'!!' often appears with:  the,  for,  to.
' New' often appears with:  so,  I, ..
'Ok' often appears with:  this,  not, !!.
' fun' often appears with: .,  it,  be.
' England' often appears with:  this,  not, !!.
' accent' often appears with:  this,  not, !!.
'L' often appears with: ol,  I, ..
'o' often appears with: ma,  I, ..
'ma' often appears with: o,  I, L.
' what' often appears with: .,  you,  I.
' mean' often appears with: .,  it,  of.
'10' often appears with:  , ., ,.
'’s' often appears with: .,  the,  it.
'Both' often appears with:  mean, ,,  .
' teams' often appears with:  mean, ,,  .
' doesn' often appears with: 't, .,  the.
' played' often appears with: ., ,,  .
' anyone' often appears with: .,  it,  doesn.
' badly' often appears with: .,  it,  mean.
' defensively' often appears with:  mean, ,,  .
' because' often appears with: .,  a, I.
'astically' often appears with:  mean, ,,  .
' game' often appears with: .,  the, ,.
' fant' often appears with:  mean, ,,  .
' goal' often appears with:  mean, ,,  .
' made' often appears with: .,  this,  me.
' works' often appears with:  hope,  it, ..
' two' often appears with: .,  the,  for.
' Cong' often appears with:  you, rats, ..
' hope' often appears with: .,  I,  you.
' happy' often appears with: .,  I,  you.
' for' often appears with: .,  the,  I.
' damn' often appears with: .,  me,  the.
'rats' often appears with:  you,  for, ..
' pretty' often appears with: .,  out,  and.
'Reading' often appears with:  you,  made,  works.
' out' often appears with: .,  the,  of.
' appealing' often appears with:  you,  think, I.
' think' often appears with: .,  you,  I.
' has' often appears with: .,  and,  that.
'untlet' often appears with:  you,  appealing,  think.
' isn' often appears with: 't, .,  that.
' ga' often appears with:  you,  appealing,  think.
'les' often appears with:  you,  appealing,  think.
'ous' often appears with: .,  you,  appealing.
' Going' often appears with:  you,  appealing,  think.
'od' often appears with: I,  you,  appealing.
' enjoy' often appears with: ., I,  I.
' cash' often appears with:  you,  and, ..
' through' often appears with: .,  to,  you.
' hide' often appears with:  you,  appealing,  think.
' grandchildren' often appears with:  you,  appealing,  think.
''re' often appears with: .,  you, ,.
' of' often appears with: .,  the,  a.
' o' often appears with:  you,  appealing,  think.
' again' often appears with: .,  that,  and.
' She' often appears with: .,  to,  the.
''t' often appears with: .,  the,  a.
' yeah' often appears with:  any, Wow,  story.
'Wow' often appears with:  my,  I,  so.
' story' often appears with:  the, .,  a.
' :(' often appears with:  I, .,  to.
' similar' often appears with:  yeah, Wow,  story.
' nightmare' often appears with:  yeah, Wow,  story.
' plan' often appears with: !,  my, 's.
''s' often appears with: .,  the,  a.
'That' often appears with: ., 's,  a.
'This' often appears with:  is, .,  I.
' funny' often appears with: .,  is,  the.
' though' often appears with: .,  still,  was.
' is' often appears with: .,  the,  a.
' Great' often appears with: .,  the, This.
' gross' often appears with: .,  the,  and.
' at' often appears with: .,  the, I.
' sweet' often appears with: .,  the,  so.
' time' often appears with: .,  the,  this.
' same' often appears with:  the, ., I.
' parenting' often appears with:  the,  Great, This.
' visit' often appears with:  the, ,,  can.
' outstanding' often appears with:  the,  visit, ,.
'Out' often appears with:  the,  visit, ,.
' can' often appears with: .,  you, ,.
' her' often appears with: .,  the,  for.
' United' often appears with:  the, .,  to.
' States' often appears with:  the,  visit, ,.
' wait' often appears with: .,  to,  the.
'standing' often appears with:  the,  visit, ,.
' group' often appears with:  the,  ,  least.
' least' often appears with:  the,  a,  I.
' m' often appears with:  the,  a,  of.
' sometimes' often appears with: ., ,,  too.
' friend' often appears with: .,  a,  of.
' lot' often appears with:  a, .,  the.
' person' often appears with:  the, ,, ..
' sucks' often appears with:  the,  time,  like.
'8' often appears with:  ,  I,  on.
'Being' often appears with:  a,  lot,  of.
'3' often appears with:  ,  the, ..
' loved' often appears with:  ,  I,  the.
' fucking' often appears with:  a,  the, NAME.
' feel' often appears with: .,  a,  I.
' like' often appears with: .,  a,  I.
' This' often appears with: .,  be,  still.
' still' often appears with: ., ,,  the.
' smith' often appears with:  This,  still,  fun.
' interested' often appears with: ., !,  This.
' available' often appears with:  This,  still,  smith.
' center' often appears with:  This,  still,  smith.
' more' often appears with: ., ,,  the.
' then' often appears with: .,  it,  I.
' season' often appears with: I,  more, ..
' am' often appears with: .,  I,  for.
' way' often appears with: .,  I,  be.
' server' often appears with:  the, ,,  making.
' making' often appears with: .,  the,  a.
' suddenly' often appears with:  a, .,  the.
' wh' often appears with:  the,  server, ,.
' must' often appears with: .,  be,  the.
'Hey' often appears with: ,, ., !.
' working' often appears with:  I, ., ,.
' sense' often appears with:  the, .,  server.
' given' often appears with:  I, ., !.
' wonder' often appears with:  the, .,  a.
' recommendations' often appears with:  the,  server, ,.
' happened' often appears with: .,  the, ,.
'ack' often appears with:  the,  server, ,.
' YouTube' often appears with:  the,  server, ,.
' today' often appears with: .,  the, ,.
' have' often appears with: .,  a, ,.
' Somebody' often appears with:  the,  server, ,.
' where' often appears with: .,  it,  that.
' problem' often appears with: .,  that,  you.
' part' often appears with: .,  that,  the.
' missed' often appears with: .,  the,  that.
'She' often appears with: .,  the,  that.
' repeating' often appears with:  the,  you,  a.
' situation' often appears with:  the,  you,  repeating.
' government' often appears with:  the,  for,  more.
' heard' often appears with: ., ,,  the.
' before' often appears with: .,  the,  I.
'Maybe' often appears with:  a,  for,  try.
' about' often appears with: .,  the,  to.
' coup' often appears with:  the,  you,  repeating.
' should' often appears with: .,  a,  the.
' cheer' often appears with:  the,  you,  about.
' learning' often appears with:  the,  you,  repeating.
' from' often appears with:  the, ., ,.
' besides' often appears with:  the,  more,  you.
' American' often appears with:  the,  you,  repeating.
' note' often appears with: .,  the,  creepy.
' creepy' often appears with:  of, .,  the.
'Super' often appears with:  is, .,  the.
' line' often appears with:  the, .,  note.
' leaving' often appears with: .,  the,  note.
' And' often appears with: .,  the,  is.
' totally' often appears with:  I, .,  it.
' forgot' often appears with:  I,  to,  totally.
'].' often appears with:  [, NAME,  the.
' Lions' often appears with:  the,  , 1.
'1' often appears with:  , .,  the.
' start' often appears with: .,  a,  to.
' started' often appears with:  the,  Lions,  .
' bad' often appears with: .,  the,  a.
'200' often appears with:  , .,  the.
' following' often appears with:  the,  Lions,  .
' franchise' often appears with:  the,  Lions,  .
' Talk' often appears with:  the,  Lions,  .
' ago' often appears with: ,,  a, ..
' year' often appears with: ,, .,  .
' technically' often appears with:  a,  wrong,  but.
' wrong' often appears with: ., ,,  I.
'Also' often appears with: .,  a,  it.
' last' often appears with: .,  the, ,.
'M' often appears with:  on, arella, oz.
'arella' often appears with: M, oz, !.
'oz' often appears with: M, arella, !.
' sticks' often appears with: M, arella, oz.
'z' often appears with: M, arella, oz.
' UP' often appears with: ,, DON,  Love.
'DON' often appears with:  UP, ,,  Love.
' Love' often appears with: .,  the,  is.
' THIS' often appears with:  UP, ,, DON.
''T' often appears with:  UP, ,, DON.
' **' often appears with: **, ,, NAME.
'**' often appears with:  **, NAME,  the.
' FUCK' often appears with: ,,  UP, DON.
'Dear' often appears with:  UP, ,, DON.
' Me' often appears with:  UP, ,, DON.
'],' often appears with: NAME,  [, ..
'’m' often appears with:  I, ., I.
' sorry' often appears with: .,  I, 'm.
' wall' often appears with:  a, .,  the.
' Wow' often appears with: .,  a,  of.
'Light' often appears with:  the, ,,  wall.
' Dem' often appears with:  the, ,,  wall.
' B' often appears with:  the, ,,  wall.
'born' often appears with:  the, ,,  wall.
'ait' often appears with:  the, ,,  wall.
' hard' often appears with: .,  to,  the.
'ise' often appears with:  the, ,,  wall.
' Look' often appears with:  the, ,,  wall.
' Slug' often appears with:  the, ,,  wall.
' flashlight' often appears with: ,,  a,  so.
'i' often appears with:  i, ,,  .
' em' often appears with: ,,  the, ..
' get' often appears with: .,  the,  I.
' Cors' often appears with: ,,  , L.
'ol' often appears with: L, ., ,.
' only' often appears with:  the, .,  I.
'The' often appears with: .,  is,  to.
' people' often appears with: .,  and,  to.
' laugh' often appears with:  I,  for, ..
' make' often appears with: .,  a, ,.
' your' often appears with: .,  you,  and.
' low' often appears with: .,  the,  you.
' work' often appears with: .,  a,  I.
' back' often appears with:  the, .,  you.
' go' often appears with: .,  to,  the.
' quality' often appears with:  the,  you,  your.
'enders' often appears with:  the,  you,  your.
' ❤' often appears with:  the,  you,  your.
'Congratulations' often appears with:  the,  you,  your.
' Hopefully' often appears with: .,  can,  the.
' resentment' often appears with:  the,  you,  your.
'️' often appears with:  you,  the,  your.
' bart' often appears with:  the,  you,  your.
' therapy' often appears with:  the,  you,  your.
' one' often appears with: .,  the,  of.
' less' often appears with:  the, .,  a.
' fortunate' often appears with:  the,  you,  a.
' too' often appears with: .,  the,  a.
' People' often appears with:  you,  is, ..
' joke' often appears with:  a, ., 's.
' helping' often appears with: ., 's,  the.
' .' often appears with: .,  the, It.
' doctors' often appears with: ,,  for,  a.
' they' often appears with: .,  the,  I.
' white' often appears with: ,,  for,  a.
' doctor' often appears with: ,,  for,  a.
' list' often appears with: ,, .,  that.
' asked' often appears with: ,,  for,  a.
' gave' often appears with: .,  me, ,.
' black' often appears with:  a,  I, I.
' swap' often appears with: -rich,  blood,  great.
'-rich' often appears with:  swap,  blood,  great.
' blood' often appears with:  swap, -rich,  great.
' great' often appears with: .,  a,  to.
' around' often appears with: .,  the,  .
'-g' often appears with:  swap, -rich,  blood.
'u' often appears with: uck,  swap, -rich.
'Would' often appears with:  it,  be,  this.
' instead' often appears with: .,  of,  if.
'ys' often appears with:  it,  swap, -rich.
'ably' often appears with:  ,  under, et.
' under' often appears with:  I,  in, ..
'et' often appears with:  I,  in,  .
' mentioned' often appears with:  in,  , ably.
' spirit' often appears with:  , ably,  under.
'Can' often appears with: .,  to,  this.
' "' often appears with: ", .,  the.
' al' often appears with:  , ably,  under.
'"?' often appears with:  , ably,  under.
' honor' often appears with:  , ably,  under.
' faces' often appears with:  cutting,  and,  their.
' cutting' often appears with:  faces,  and,  their.
' neighbors' often appears with:  faces,  cutting,  and.
' joking' often appears with:  faces,  cutting,  and.
' holding' often appears with:  faces,  cutting,  and.
' It' often appears with: ., 's,  to.
' here' often appears with: ., ,,  to.
'These' often appears with: .,  people,  are.
' down' often appears with: .,  and, ,.
' gets' often appears with:  a,  and, NAME.
' hired' often appears with:  hope,  gets, NAME.
' does' often appears with:  that, .,  is.
' up' often appears with: .,  to,  the.
' by' often appears with: .,  the,  to.
' every' often appears with: ., ,,  I.
'Yeah' often appears with: .,  I,  a.
' unfortunately' often appears with:  up,  does,  .
'20' often appears with:  ,  that,  the.
' being' often appears with: .,  I, ,.
' i' often appears with: .,  to,  and.
'g' often appears with:  a, .,  om.
' gorgeous' often appears with:  a,  looks,  still.
'gg' often appears with:  still,  for,  a.
' looks' often appears with: .,  like, NAME.
' Sh' often appears with:  still,  for,  a.
'es' often appears with: .,  a, 's.
' dying' often appears with:  for, .,  like.
' shore' often appears with:  still,  for,  a.
' jersey' often appears with: .,  a,  is.
' she' often appears with: .,  to, ,.
'assi' often appears with:  still,  for,  a.
' St' often appears with: .,  at,  still.
'O' often appears with: .,  like, mg.
' going' often appears with: .,  it,  to.
' look' often appears with: .,  a,  and.
'INK' often appears with: ,,  sugar,  Keep.
' sugar' often appears with: ,, INK,  Keep.
' Keep' often appears with: ,,  your, ..
'Y' often appears with: ,,  and, ..
'up' often appears with: ,, INK,  sugar.
' helps' often appears with:  and, ., ,.
' water' often appears with:  and, ., !.
' anymore' often appears with: .,  you, NAME.
'...' often appears with: .,  I,  the.
' DR' often appears with: ,, INK,  sugar.
' comments' often appears with:  I, .,  are.
' ignored' often appears with:  the,  This,  for.
' attention' often appears with: .,  I,  comments.
' THEY' often appears with:  the,  This,  for.
' type' often appears with: .,  the,  I.
' troll' often appears with:  I, .,  should.
' looking' often appears with: .,  the,  for.
' amazing' often appears with: ., !,  is.
' thought' often appears with:  was,  a,  that.
' boy' often appears with: I,  I,  a.
' broke' often appears with:  thought,  then,  boy.
' high' often appears with:  and,  to,  of.
' key' often appears with:  thing,  when,  is.
' thing' often appears with: .,  the,  I.
' hours' often appears with:  thought,  then,  boy.
' meantime' often appears with: ed,  Switch, m.
'ed' often appears with: .,  it,  a.
' Switch' often appears with:  meantime, ed, m.
'm' often appears with:  meantime, ed,  Switch.
'Me' often appears with: .,  meantime, ed.

In [21]:
instruction = (
    "You are a data generator tasked with creating realistic Reddit comments. "
    "These comments should be labeled according to their sentiment: positive or negative.\n"
    "Base the style on typical Reddit comments — include informal internet language, typos, abbreviations, and emojis.\n"
    "You will be given information about token co-occurences which provides information on which words appear near each other.\n"
    "Use [NAME] as a placeholder anytime a person's name would appear.\n"
    "Generate exactly 10 realistic Reddit comments, one per line.\n"
    "Each line should follow this format: the comment in double quotes, followed by a space and then the label (1 for positive, -1 for negative).\n"
    "No extra formatting — just plain text output, one line per comment.\n"
    "Here is the format:\n"
    "\"I love pizza\" 1\n"
    "\"I hate baseball\" -1"
)
input = (
    f"Here are the token co-occurences ordered by frequency:\n{summary_text}",
    f"Now, generate the 10 new comments below:"
)

In [36]:
response = client.responses.create(
        model="gpt-4o",
        instructions=instruction,
        input=input[0]
    )
print(response.output_text)

1. "Well, I’m glad you enjoyed the game!" 1
2. "I’m so tired of this ridiculous weather." -1
3. "Fantastic job on the project, keep it up!" 1
4. "I can’t believe how bad the movie was..." -1
5. "Honestly, that was the most amazing story!" 1
6. "The customer service here is just awful." -1
7. "I hope your day is going great so far." 1
8. "Why is this game always bugging out? Ugh." -1
9. "You’re doing a fantastic job, congrats!" 1
10. "Ugh, I can’t stand the traffic here." -1

In [44]:
res = []
for i in tqdm(range(30)):
    response = client.responses.create(
        model="gpt-4o",
        instructions=instruction,
        input=input[0]
    )
    res.append(response.output_text)

  0%|          | 0/30 [00:00<?, ?it/s]

100%|██████████| 30/30 [05:42<00:00, 11.43s/it]

In [41]:
res

['"I’m so glad I found this community! Everyone here is super helpful and welcoming. 😊" 1  \n"Ugh, this really sucks. I can\'t believe people actually enjoy this nonsense." -1  \n"Wow, I just finished that book and it was absolutely fantastic! Couldn\'t put it down!" 1  \n"I thought my day couldn\'t get any worse, then I read this mess. 😒" -1  \n"I can\'t express how happy I am. Everything went so smoothly today!" 1  \n"This company’s management is so frustrating, nothing ever gets done right. 😠" -1  \n"Glad I joined this project, the team is amazing and I’ve learned a ton!" 1  \n"Honestly, this has been a complete waste of time. Can\'t recommend it at all." -1  \n"Had a great time at the event yesterday. Met some awesome people and learned lots!" 1  \n"I hate when things are so disorganized. It’s just exhausting dealing with it." -1  ',
 '"I\'m so glad you shared that experience! 😊" 1  \n"Honestly, it was a terrible movie." -1  \n"Your post made my day! Thanks for sharing!" 1  \n"Ugh, I can\'t believe I wasted time on this." -1  \n"That was a fantastic game, loved every moment!" 1  \n"Wow, that was a disappointing result... 😒" -1  \n"Happy you enjoyed the event, sounds awesome!" 1  \n"Can\'t stand how they handled this situation." -1  \n"Have a great day, everyone! 😊" 1  \n"Not happy about the service here, really not." -1',
 '"I\'m so glad that movie was awesome!" 1\n"Why do people waste their time on such terrible shows?" -1\n"I\'m really happy you found your lost dog!" 1\n"The game was a major disappointment, just awful." -1\n"I could see that the concert was fantastic!" 1\n"This pizza place is gross, never eating here again." -1\n"I love how you always cheer me up!" 1\n"Ugh, the service here is horrible, never coming back." -1\n"Reading your comments always makes my day better!" 1\n"The new update is just confusing and buggy." -1',
 '"I’m so glad to see the positive changes in the community!" 1  \n"That movie was a total letdown, couldn’t stand it." -1  \n"Really appreciate the effort, the art turned out amazing!" 1  \n"Feeling pretty down today, everything seems off :(" -1  \n"It’s fantastic how you managed to pull this off!" 1  \n"Honestly, I don’t see the point in continuing this discussion." -1  \n"Wow, your idea worked out perfectly!" 1  \n"Can’t believe how frustrating this situation is." -1  \n"Congrats on your new job, sounds exciting!" 1  \n"Ugh, this update ruined everything for me." -1',
 '"I’m so glad you shared this story. It really made my day better 😊" 1  \n"I can\'t believe how bad that movie was, total waste of time 😒" -1  \n"This game is fantastic! I’ve been playing for hours and loving every minute." 1  \n"Honestly, I was quite disappointed with the new update, it sucks." -1  \n"I just wanted to say thank you for your kind words, it means a lot!" 1  \n"Super frustrating when the app doesn’t work properly. Fix it already!" -1  \n"Congrats on your graduation, you really deserve it! 🎉" 1  \n"Why do they make the system so difficult? It’s really annoying!" -1  \n"Your cake looks amazing, happy birthday to you! 🎂" 1  \n"The customer service was terrible, didn’t help me at all." -1',
 '1. "I’m so glad it’s Friday! 🥳" 1\n2. "Ugh, can’t believe I have to deal with this crap again... 🤦\u200d♀️" -1\n3. "Had a fantastic weekend with friends! 😄" 1\n4. "This whole situation is just ridiculous and annoying." -1\n5. "Feeling pretty good about my achievements this week!" 1\n6. "I’m tired of this constant stress 😩" -1\n7. "Wow, the new update is amazing! 😍" 1\n8. "Not sure why everything has to be so complicated." -1\n9. "The weather today is perfect! ☀️" 1\n10. "Honestly, I’m really disappointed with how things turned out." -1',
 '"I’m so glad you’re here, makes my day better 😊." 1  \n"Couldn’t believe how terrible that game was, it was a total nightmare." -1  \n"Well, I’m really happy for you, congrats on the improvement!" 1  \n"It’s not obvious how frustrating this is, I can’t stand it!" -1  \n"Honestly, the way you’ve handled this is fantastic, well done!" 1  \n"This whole situation is a mess, like what even happened here?" -1  \n"Good luck with everything, hope it all goes your way!" 1  \n"I’m annoyed at how poorly that worked out, totally forgot about it." -1  \n"Wow, seeing you so happy makes me smile 😊." 1  \n"Ugh, the way things turned out is just sad, didn’t expect this." -1  ',
 '"Glad to help you out today! :)" 1  \n"Really hate how things turned out..." -1  \n"Fantastic day for a walk, the weather is perfect." 1  \n"I\'m not a fan of this new update, it\'s just bad." -1  \n"Couldn’t have asked for a better outcome, honestly." 1  \n"Why does this game have so many bugs? Ugh." -1  \n"Absolutely thrilled with this performance!" 1  \n"I don’t understand why this keeps happening, so frustrating." -1  \n"Happy to finally see these improvements, great job!" 1  \n"This was a terrible decision, who approved this??" -1',
 '"I\'m glad you could enjoy the movie, it was fantastic!" 1  \n"Did you see the scary situation today? It was awful." -1  \n"Isn\'t it obvious we love when you come over, always great!" 1  \n"I don\'t think those games are fun anymore, totally boring." -1  \n"Congrats on your promotion, that\'s so awesome!" 1  \n"The new update is pretty disappointing, honestly." -1  \n"So glad I went hiking today, the views were spectacular!" 1  \n"Your attempt was a failure, it sucks." -1  \n"Thanks for the invite, the party was a blast!" 1  \n"Sorry to hear about your tough day, hope it gets better." -1',
 '1. "I\'m so glad you enjoyed the party! 🎉" 1\n2. "I can\'t believe how bad that episode was... 😞" -1\n3. "Just got a new job, feeling fantastic about it!" 1\n4. "Why is this game so laggy, it\'s driving me nuts!" -1\n5. "Have a fantastic day ahead, you deserve it!" 1\n6. "Ugh, my internet isn\'t working, I\'m so frustrated." -1\n7. "Congratulations on your achievement, well done! 🏆" 1\n8. "Seriously, the service here sucks. 😒" -1\n9. "I\'m happy to help, just let me know what you need. 😊" 1\n10. "This place is a nightmare, can\'t wait to leave." -1',
 '"I’m so glad I decided to take the day off, it’s been fantastic so far!" 1  \n"Ugh, I don’t know how they could ruin such a great show, terrible decision." -1  \n"Wow, that was such an amazing game last night! I’m still hyped." 1  \n"Can\'t believe I wasted money on that trash, never doing that again." -1  \n"The concert last night was outstanding, love to see live music back!" 1  \n"I’m really disappointed with the service at that place, never going back." -1  \n"Your post always makes my day better, keep it up! 😊" 1  \n"Why do these updates keep getting worse? It\'s so frustrating!" -1  \n"So happy to hear about your promotion, congrats! 🎉" 1  \n"Another delay, great! As if I wasn\'t already irritated enough." -1',
 '"I’m so glad I found this thread, it’s fantastic!" 1  \n"Ugh, this is such a mess, I can’t even." -1  \n"Wow, I’m really happy about this improvement!" 1  \n"This situation is downright horrifying, isn’t it?" -1  \n"Have a great day, hope it shines bright!" 1  \n"I can’t believe they messed up again, it’s infuriating." -1  \n"Reading your comment made my day better, thanks!" 1  \n"Honestly, the way they handled this is quite terrible." -1  \n"Good luck with everything, rooting for you!" 1  \n"Why does this always happen? I\'m so frustrated." -1  ',
 '"I’m glad to see you’re happy!" 1  \n"Well, that was a waste of time." -1  \n"Didn’t expect things to turn out this good!" 1  \n"I’m so tired of this nonsense." -1  \n"Hope you have a fantastic day 😊" 1  \n"This really pisses me off!" -1  \n"OMG, I couldn’t stop laughing 😂" 1  \n"Feeling pretty sad about how it turned out." -1  \n"Glad you shared your experience with us!" 1  \n"Ugh, I don’t think I can handle this anymore." -1',
 '"I\'m glad I could be there for you today!" 1  \n"Too bad the game was a disappointment." -1  \n"Honestly, that was a fantastic turn of events!" 1  \n"I\'m not really interested in that topic, sorry." -1  \n"Have a great day, you\'re doing amazing!" 1  \n"This project was poorly managed from the start." -1  \n"I bet you\'d love the taste of this dish." 1  \n"That decision was completely unnecessary, IMO." -1  \n"So happy to see your progress, well done!" 1  \n"I can’t believe they ignored the feedback again!" -1',
 '1. "Wow, that concert was amazing! 🎸 Had so much fun." 1  \n2. "Ugh, I can\'t stand when traffic is this awful. 😡" -1  \n3. "Just got a promotion at work! So pumped! 🎉" 1  \n4. "Not a fan of this weather, super depressing. ☔" -1  \n5. "Managed to get tickets for the big game, can\'t wait! 🏈" 1  \n6. "Feeling so sick, this cold is the worst. 🤒" -1  \n7. "Best vacation ever, the beach was incredible! 🏖️" 1  \n8. "My package got lost in the mail, super frustrating. 📦" -1  \n9. "Finished the project early, it turned out fantastic. 🏆" 1  \n10. "The new update ruined the game, not even fun anymore. 🎮" -1',
 '"I’m glad you’re happy with the improvement!" 1  \n"This is just so disappointing." -1  \n"I could use some help, thanks!" 1  \n"Seriously, the game was awful and boring." -1  \n"Love the way you handled that situation." 1  \n"It’s obvious the outcome was terrible." -1  \n"Congrats on the job, you deserve it!" 1  \n"The sound quality is really bad." -1  \n"Glad to hear things are improving for you!" 1  \n"I’m not seeing any improvement, honestly." -1',
 '"I’m really glad you’re here, the weather could be worse." 1  \n"Man, this day just keeps getting worse and worse." -1  \n"LOL that was such a fantastic move on their part!" 1  \n"Not gonna lie, I’m kind of scared to take the plunge." -1  \n"WHAT an improvement in the game, isn’t it?" 1  \n"Pretty sad how they won’t let us enjoy the simple things." -1  \n"Finally, seeing it all come together was worth the wait!" 1  \n"Did you hear how terrifying the whole event was?" -1  \n"Glad they found a way to make it work!" 1  \n"The customer service is just plain awful!" -1',
 '"I\'m so glad you shared this story. Made my day! 😊" 1  \n"Honestly, that was a pretty disappointing update." -1  \n"Wow, what an incredible thing to witness! Truly awesome!" 1  \n"I can\'t stand how this game could be so infuriating..." -1  \n"Congrats on your achievement! 🎉 You\'re amazing." 1  \n"I tried it and it was a complete waste of time." -1  \n"You nailed it! Such a fantastic piece of art." 1  \n"It sucks that the service was bad today." -1  \n"So happy for you, that\'s great news!" 1  \n"I can\'t believe I had to deal with this nonsense again." -1  ',
 '"I\'m so glad that I could help!" 1  \n"Not gonna lie, that was terrible." -1  \n"This is an outstanding improvement!" 1  \n"Honestly, the whole thing scared me :(" -1  \n"It was a really good day :)" 1  \n"Ugh, I hate when that happens." -1  \n"Wow, that show was fantastic!" 1  \n"You better not piss me off..." -1  \n"Pretty sure I’ll be happy with this." 1  \n"Why is it always so awful?" -1',
 '"I’m so glad we could meet today!" 1\n"Not gonna lie, this weather is the worst." -1\n"Have a fantastic day, everyone! 😊" 1\n"These prices are absolutely insane... 😡" -1\n"Great to see you’re doing well! 👍" 1\n"Didn’t expect this to be so bad." -1\n"Wow, this really just made my day! 😄" 1\n"I’m tired of their service, it sucks!" -1\n"Love the improvement in my mood lately." 1\n"Honestly, your game is just annoying." -1',
 '"I\'m so glad I started yoga, it\'s been fantastic for my mental health 😊" 1  \n"This game was so disappointing, I can\'t believe I wasted money on it 😔" -1  \n"I\'m really happy to hear about your promotion, congratulations! 🎉" 1  \n"It was a terrible mistake, never trusting that company again 🤬" -1  \n"I had such a fun day at the park with friends!" 1  \n"Honestly, this movie was a waste of time, wouldn\'t recommend it." -1  \n"Just got the new phone and it\'s amazing! The camera quality is fantastic 📱" 1  \n"Ugh, another day ruined by this awful weather, can\'t stand it" -1  \n"Caught up with an old friend and it was lovely to reconnect." 1  \n"Why is everything breaking at the worst time? So frustrating..." -1',
 '"I\'m so glad I found this thread, it\'s super helpful!" 1  \n"Honestly, this could not be more disappointing." -1  \n"I can\'t believe how fantastic the artwork was!" 1  \n"Ugh, the experience was pretty horrendous." -1  \n"I\'m happy you think the same, let\'s keep it positive!" 1  \n"Not thrilled with the way things turned out at all." -1  \n"Congrats on your success, really happy for you!" 1  \n"I regret wasting time on this, it was a total disaster." -1  \n"Enjoying these weekends so much, thank you all!" 1  \n"It\'s annoying how often this happens, seriously frustrating." -1  ',
 '1. "Well, I’m glad I found this community, so many fantastic people!" 1\n2. "I can’t stand how annoying this situation is. Ugh." -1\n3. "Finally, I got the chance to see this improvement, and it\'s awesome!" 1\n4. "Could it be any worse? This place is driving me nuts!" -1\n5. "Wow, the way this plan was executed is simply brilliant!" 1\n6. "I hate how the system always lets us down." -1\n7. "It’s so nice to see everyone come together and help out!" 1\n8. "Not again! This has been the most frustrating day ever." -1\n9. "Good to hear about your progress. Keep it up, my friend!" 1\n10. "That was a terrible game, honestly, couldn’t have been any worse!" -1',
 '"Glad to have such a fantastic day with you! 🌟" 1  \n"Ugh, the weather today is making me sad." -1  \n"I’m so glad we could hang out and have a great time!" 1  \n"This situation is super annoying, can\'t stand it anymore." -1  \n"Well, I finally got my new phone and it\'s fantastic!" 1  \n"Honestly, I\'m so tired of dealing with this nonsense." -1  \n"Not gonna lie, seeing you smile today made my day." 1  \n"I\'m feeling pretty down after hearing that news." -1  \n"Great to hear you\'re doing well, keep it up! 💪" 1  \n"Why does this always have to happen to me? 😩" -1',
 '"I\'m glad we could help!" 1  \n"Ugh, today was a nightmare." -1  \n"Fantastic game! Loved every second of it." 1  \n"This mechanic is so broken, it pisses me off." -1  \n"Glad to see the improvements, well done!" 1  \n"Why do these bugs appear every time? So frustrating." -1  \n"What a great day, everything went smoothly!" 1  \n"I\'m not a fan of the new update, it\'s terrible." -1  \n"Enjoying this so far! Thanks for the suggestion." 1  \n"Can\'t believe they ruined the series with this season." -1',
 '"I\'m so glad I found this fantastic community!" 1  \n"Ugh, I can\'t believe how awful the service was today." -1  \n"Hey, just wanted to say you’re doing a great job. Keep it up!" 1  \n"Honestly, I’m pissed off that they still haven’t fixed this issue." -1  \n"She’s such a kind person, always helping others without hesitation." 1  \n"Why do people act so rude? It really ruins the vibe." -1  \n"This place is amazing, I can’t wait to come back again!" 1  \n"That game was a total disappointment, I expected better." -1  \n"Reading your comments always makes my day brighter 😊" 1  \n"Don\'t you just hate it when your stuff gets lost?" -1',
 '1. "Glad I could help you out with that project! 😊" 1\n2. "Ugh, I can\'t believe they missed that goal again, so frustrating." -1\n3. "You made my day, that was truly uplifting!" 1\n4. "Wow, that really pissed me off, can\'t believe it!" -1\n5. "Congrats on the new job, you deserve it!" 1\n6. "I hate it when people act like they\'re better than everyone." -1\n7. "Finally got to visit the beach, it was fantastic!" 1\n8. "Not feeling well today, this sucks." -1\n9. "Well, your advice was spot on, thanks a lot!" 1\n10. "That movie was a total waste of time, so bad!" -1',
 '"I\'m so glad you could make it, this place is fantastic!" 1  \n"Ugh, I’m not feeling well today, everything sucks." -1  \n"Have a great day, hope you enjoy it!" 1  \n"Well, that was a complete waste of time, I\'m pissed." -1  \n"What a fantastic improvement, keep it up!" 1  \n"Damn, I totally forgot about that, so annoying." -1  \n"Congratulations on the new addition to your family!" 1  \n"Honestly, this constant waiting is super frustrating." -1  \n"Reading your story made my day a little brighter." 1  \n"I’m so tired of this same old routine, it\'s draining." -1',
 '"I’m so glad we had this talk!" 1  \n"This service is absolutely horrible!" -1  \n"Finally watched the new show and it’s fantastic!" 1  \n"Ugh, why did I waste my time on this movie?" -1  \n"Congrats on the new job, hope it\'s amazing!" 1  \n"I’m still pissed about how they handled it." -1  \n"Your support means a lot to me, thank you!" 1  \n"I\'d never recommend that place to anyone, ever." -1  \n"Got a new phone and it’s pretty cool so far." 1  \n"Tried the food there, and it was a disaster." -1  ',
 '"I\'m glad I found this sub, the community is so supportive!" 1  \n"Well, the app\'s user interface is honestly quite terrible." -1  \n"I could\'ve bought a new game, but this sale was too fantastic to pass up!" 1  \n"Ugh, the amount of ads in this game is disgusting, absolutely ruined the experience." -1  \n"Thanks for all the tips, they really helped me improve my skills." 1  \n"The plot of this film was painfully predictable and boring." -1  \n"What a sweet surprise, you deserve all the happiness!" 1  \n"It\'s sad that the management doesn\'t care about the user feedback." -1  \n"The scenery here is breathtaking, definitely recommend visiting!" 1  \n"I hate how the updates always break something in the app." -1',
 '"I’m really happy to hear about your success! 🥳" 1  \n"Ugh, this whole thread is just disappointing..." -1  \n"Congrats! You deserve all the good things coming your way. 😊" 1  \n"This news is absolutely horrifying." -1  \n"So glad you’re doing well! Keep it up!" 1  \n"I’m feeling really sad about what happened." -1  \n"You did an amazing job, keep shining! ✨" 1  \n"That was such a waste of time." -1  \n"Glad to see such fantastic improvement today. 🙌" 1  \n"This situation is just so frustrating right now." -1',
 '"I am so glad we\'re going to the beach today! It\'s been a while since I\'ve had some sun!" 1  \n"This game is a total disappointment, I can\'t believe I spent money on it." -1  \n"After a rough week, this news is just what I needed to hear! 😊" 1  \n"I hate how the update ruined the interface, it\'s so bad now. 😠" -1  \n"Finally finished that project! Feels amazing to wrap it up. 🎉" 1  \n"Ugh, this week has been such a bummer, just can\'t catch a break." -1  \n"Got promoted today, couldn\'t be happier! 🎉" 1  \n"This concert was a total waste of time, wish I hadn\'t gone." -1  \n"Just received a surprise gift, totally made my day! 😊" 1  \n"Everything seems to be going wrong lately, can\'t stand it anymore." -1',
 '"I’m so glad you could make it!" 1  \n"Did you really think that was a good idea?" -1  \n"I\'m glad you finally tried it, it\'s fantastic." 1  \n"I can\'t stand how annoying these glitches are." -1  \n"What a fantastic improvement on the game, congrats to the dev team!" 1  \n"That episode scared the hell out of me, tbh." -1  \n"So happy to hear your good news, congrats!" 1  \n"I\'m totally pissed off with this update." -1  \n"Seeing such a beautiful sunset made my day." 1  \n"Ugh, this is just a sad situation all around." -1',

In [45]:
labels = []
sentences = []
for i in range(30):
    for word in res[i].split("\n"):
        match = re.match(r'"(.*?)"\s*(-?\d+)', word)
        if match:
            quoted = match.group(1)      
            label = match.group(2)       
            sentences.append(quoted)
            labels.append(int(label))

In [46]:
generated_df = pd.DataFrame({
    'sentences': sentences,
    'labels': labels
})

In [47]:
generated_df

                                             sentences  labels
0             I’m glad that movie was so entertaining!       1
1         Ugh, I can't stand when they mess up orders.      -1
2    Great game last night, the players were fantas...       1
3           Why does this keep happening? So annoying.      -1
4           Their new album dropped and it's amazing!!       1
..                                                 ...     ...
245              Another day, another boring meeting 😒      -1
246  So glad I went for a walk today, feeling refre...       1
247    That game last night was pretty disappointing 😞      -1
248   Just finished a great book and loved every page!       1
249             I hate it when my internet goes down 😡      -1

[250 rows x 2 columns]

In [48]:
first_df

                                             sentences  labels
0    I’m so glad I found this community! Everyone h...       1
1    Ugh, this really sucks. I can't believe people...      -1
2    Wow, I just finished that book and it was abso...       1
3    I thought my day couldn't get any worse, then ...      -1
4    I can't express how happy I am. Everything wen...       1
..                                                 ...     ...
855     Well, that’s just a nightmare scenario, sorry.      -1
856            Happy to see improvement in their game.       1
857     I don’t know how to deal with all this stress.      -1
858          It’s great seeing you here, welcome back!       1
859   I’m not impressed with this situation, honestly.      -1

[860 rows x 2 columns]

In [50]:
combined = pd.concat([first_df, generated_df])

In [52]:
combined.to_csv('../data/generated/reddit/token_co_occurences/token_co_occurences.csv', index=False)